In [625]:
import pandas as pd
import jieba
import re
import wordcloud
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer  
import numpy as np
from sklearn.feature_extraction.text import TfidfTransformer  
from sklearn.decomposition import PCA
import warnings
warnings.filterwarnings("ignore")
from sklearn.cluster import KMeans
from sklearn.decomposition import LatentDirichletAllocation
import mglearn

In [626]:
data_2018=pd.read_excel("./low_2018.xlsx")

In [627]:
data_2018.head()

,mid,日期,内容,转发数,评论数,点赞数,来自,博主,uid,是否已认证,认证内容
0,4323349901735420,2018-12-31 18:00,输卵管具有运送精子、摄取卵子及把受精卵运送到子宫腔的重要作用， 一旦发生堵塞、积水、不通等，...,NaN,NaN,NaN,深圳怡康妇产医院V,微博 weibo.com,6362406344,True,深圳怡康妇产医院官方微博
1,4323327252420440,2018-12-31 16:30,【怡康喜报】二胎政策放开后，张女士全家特别想再要一个孩子。取环后，夫妻俩积极备孕，多次尝试，...,NaN,NaN,NaN,深圳怡康妇产医院V,微博 weibo.com,6362406344,True,深圳怡康妇产医院官方微博
2,4323305915956700,2018-12-31 15:05,#不孕不育#宜正堂 治疗不孕不育20年 ，不孕不育的专家 联系电话1662116...,NaN,NaN,NaN,宜正堂,vivo AI智慧拍照X21,6906732347,False,NaN
3,4323214005703270,2018-12-31 09:00,为什么怀孕了，建议大家及时去做早孕检查。是因为大家在做试纸检测的时候，所操作方法和试纸厂家存...,NaN,NaN,NaN,深圳怡康妇产医院V,微博 weibo.com,6362406344,True,深圳怡康妇产医院官方微博
4,4323041046146520,2018-12-30 21:32,#南宁 不孕不育 试管移植失败#宜正堂 治疗不孕不育的专家 联系电话166211...,NaN,NaN,NaN,宜正堂,vivo AI智慧拍照X21,6906732347,False,NaN

In [568]:
data_2018.shape

(1960, 11)

In [569]:
data_2018=data_2018[["内容"]]

In [570]:
data_2018.head()

                                                  内容
0  输卵管具有运送精子、摄取卵子及把受精卵运送到子宫腔的重要作用， 一旦发生堵塞、积水、不通等，...
1  【怡康喜报】二胎政策放开后，张女士全家特别想再要一个孩子。取环后，夫妻俩积极备孕，多次尝试，...
2  #不孕不育#宜正堂   治疗不孕不育20年   ，不孕不育的专家   联系电话1662116...
3  为什么怀孕了，建议大家及时去做早孕检查。是因为大家在做试纸检测的时候，所操作方法和试纸厂家存...
4  #南宁  不孕不育  试管移植失败#宜正堂   治疗不孕不育的专家   联系电话166211...

In [571]:
data_2018=data_2018.drop_duplicates()

In [572]:
data_2018.head()

                                                  内容
0  输卵管具有运送精子、摄取卵子及把受精卵运送到子宫腔的重要作用， 一旦发生堵塞、积水、不通等，...
1  【怡康喜报】二胎政策放开后，张女士全家特别想再要一个孩子。取环后，夫妻俩积极备孕，多次尝试，...
2  #不孕不育#宜正堂   治疗不孕不育20年   ，不孕不育的专家   联系电话1662116...
3  为什么怀孕了，建议大家及时去做早孕检查。是因为大家在做试纸检测的时候，所操作方法和试纸厂家存...
4  #南宁  不孕不育  试管移植失败#宜正堂   治疗不孕不育的专家   联系电话166211...

In [573]:
def remove_hashtags(text):
    # 使用正则表达式匹配两个#之间的内容，并替换为空字符串
    cleaned_text = re.sub(r'#(.*?)#', '', text)
    return cleaned_text

In [574]:
#删除话题标志
data_2018["内容"]=data_2018["内容"].apply(lambda x:remove_hashtags(x))

In [575]:
#用大模型判断是否是不孕不育话题
import requests
def send_post(url,data):
    try:
        response = requests.post(url, json=data)
        if response.status_code == 200:
            #             print("POST request was successful!")
            #             print("Response data:")
            return response.json()
        else:
            print(f"POST request failed with status code: {response.status_code}")
    except requests.exceptions.RequestException as e:
        print(f"Error occurred: {e}")
url="http://180.76.49.225:7861/chat"

In [576]:
realt_flag=[]

In [ ]:
for cont in data_2018["内容"].values:
    data={"question":"请帮我判断以下文本是否关于不孕不育、生育或者怀孕的话题，如果是，请直接输出一个字是，否则直接输出不是，务必不要返回其他内容。文本是："+cont}
    realt_flag.append(send_post(url,data)["answer"])

In [555]:
data_2018["relat"]=realt_flag

In [556]:
data_2018=data_2018[data_2018["relat"].apply(lambda x:x=="是")]

In [560]:
data_2018.shape

(1602, 2)

In [561]:
data_2018.to_excel("./2018_rel.xlsx")

In [710]:
data_2018=pd.read_excel("./2018_rel.xlsx")

In [711]:
#替换名称
cn_city=["四川省","四川","南岳","上海","广州","深圳","东莞","重庆","北京","合肥","郑州","天津","无锡","南宁","忻州","长沙","南宁",
         "南王","漕河镇","黄冈","湖南","十安","湖南","十安","南京","信阳","沈阳","台湾","汕头","广东","河北","郴州","邯郸","海口"]
out_city=["法国","泰国","澳洲","乌克兰","曼谷","马来西亚","英国政府","美国","欧洲","阿德莱德","俄罗斯"]
person=["顾岩","田纪香","王丽敏","王铁梅","铁梅","庹有烈","匡淑杰","田平君","田平","医羽","爱问","张潇潇","李媛","崔娟","郑芬芬"]
hospi=["怡康","九院","百佳","宝来佳运","恒健","济爱","宜正堂","卫人","仁和","北辰","朝阳医院","衍宗堂","和睦家","仁爱医院","华博"]

In [712]:
def replace(ss):
    for c in cn_city:
        ss=ss.replace(c,"国内")
    for c in out_city:
        ss=ss.replace(c,"国外")
    for c in person:
        ss=ss.replace(c,"医生")
    for c in hospi:
        ss=ss.replace(c,"医院")
    return ss

In [713]:
data_2018["内容"]=data_2018["内容"].apply(lambda x:replace(x))

In [714]:
#只保留中文
data_2018["content2"]=data_2018["内容"].apply(lambda x:re.sub(r'[^\u4e00-\u9fa5]','',str(x)))

In [715]:
jieba.add_word("公众号")

In [716]:
#结巴分词
data_2018["words"]=data_2018["content2"].apply(lambda x:jieba.lcut(x))

In [717]:
data_2018.head()

,Unnamed: 0,内容,relat,content2,words
0,0,输卵管具有运送精子、摄取卵子及把受精卵运送到子宫腔的重要作用， 一旦发生堵塞、积水、不通等，...,是,输卵管具有运送精子摄取卵子及把受精卵运送到子宫腔的重要作用一旦发生堵塞积水不通等需要及时治疗...,"[输卵管, 具有, 运送, 精子, 摄取, 卵子, 及, 把, 受精卵, 运送, 到, 子宫..."
1,1,【医院喜报】二胎政策放开后，张女士全家特别想再要一个孩子。取环后，夫妻俩积极备孕，多次尝试，...,是,医院喜报二胎政策放开后张女士全家特别想再要一个孩子取环后夫妻俩积极备孕多次尝试可一年多过去了...,"[医院, 喜报, 二胎, 政策, 放开, 后, 张女士, 全家, 特别, 想, 再, 要, ..."
2,2,医院 治疗不孕不育20年 ，不孕不育的专家 联系电话16621161987微信同...,是,医院治疗不孕不育年不孕不育的专家联系电话微信同号国内武鸣县城厢镇,"[医院, 治疗, 不孕, 不育, 年, 不孕, 不育, 的, 专家, 联系电话, 微信, 同..."
3,3,为什么怀孕了，建议大家及时去做早孕检查。是因为大家在做试纸检测的时候，所操作方法和试纸厂家存...,是,为什么怀孕了建议大家及时去做早孕检查是因为大家在做试纸检测的时候所操作方法和试纸厂家存放时间...,"[为什么, 怀孕, 了, 建议, 大家, 及时, 去, 做, 早孕, 检查, 是因为, 大家..."
4,4,医院 治疗不孕不育的专家 联系电话16621161987 2国内·那洪街区 ​,是,医院治疗不孕不育的专家联系电话国内那洪街区,"[医院, 治疗, 不孕, 不育, 的, 专家, 联系电话, 国内, 那洪, 街区]"

In [718]:
#读停用词
StopDictionary_path = './stop_words.txt'  #stop_words_2018
stop_words = []

In [719]:
pd.DataFrame(stop_words).to_csv("./2018_stopword.csv")

In [720]:
# 加载停用词
def get_stopwords(filePath):
    global stop_words
    f = open(filePath, 'r', encoding='utf8', errors='ignore')
    line = f.readline()
    while line:
        stop_words.append(line.strip())
        line = f.readline()
    f.close()

In [721]:
get_stopwords(StopDictionary_path)

In [722]:
#去掉数据中的停用词
def drop_stop_words(arr):
    word_clean=[]
    for w in arr:
        if len(w)>=2 and w not in stop_words:
            word_clean.append(w)
    return word_clean

In [723]:
data_2018["words_clean"]=data_2018["words"].apply(lambda x:drop_stop_words(x))

In [724]:
data_2018.head()

,Unnamed: 0,内容,relat,content2,words,words_clean
0,0,输卵管具有运送精子、摄取卵子及把受精卵运送到子宫腔的重要作用， 一旦发生堵塞、积水、不通等，...,是,输卵管具有运送精子摄取卵子及把受精卵运送到子宫腔的重要作用一旦发生堵塞积水不通等需要及时治疗...,"[输卵管, 具有, 运送, 精子, 摄取, 卵子, 及, 把, 受精卵, 运送, 到, 子宫...","[输卵管, 运送, 精子, 摄取, 卵子, 受精卵, 运送, 子宫腔, 作用, 发生, 堵塞..."
1,1,【医院喜报】二胎政策放开后，张女士全家特别想再要一个孩子。取环后，夫妻俩积极备孕，多次尝试，...,是,医院喜报二胎政策放开后张女士全家特别想再要一个孩子取环后夫妻俩积极备孕多次尝试可一年多过去了...,"[医院, 喜报, 二胎, 政策, 放开, 后, 张女士, 全家, 特别, 想, 再, 要, ...","[医院, 喜报, 二胎, 政策, 放开, 全家, 特别, 孩子, 取环后, 夫妻俩, 备孕,..."
2,2,医院 治疗不孕不育20年 ，不孕不育的专家 联系电话16621161987微信同...,是,医院治疗不孕不育年不孕不育的专家联系电话微信同号国内武鸣县城厢镇,"[医院, 治疗, 不孕, 不育, 年, 不孕, 不育, 的, 专家, 联系电话, 微信, 同...","[医院, 治疗, 不孕, 不育, 不孕, 不育, 专家, 联系电话, 同号, 国内, 武鸣县..."
3,3,为什么怀孕了，建议大家及时去做早孕检查。是因为大家在做试纸检测的时候，所操作方法和试纸厂家存...,是,为什么怀孕了建议大家及时去做早孕检查是因为大家在做试纸检测的时候所操作方法和试纸厂家存放时间...,"[为什么, 怀孕, 了, 建议, 大家, 及时, 去, 做, 早孕, 检查, 是因为, 大家...","[怀孕, 建议, 早孕, 检查, 试纸, 检测, 操作方法, 试纸, 厂家, 存放, 时间,..."
4,4,医院 治疗不孕不育的专家 联系电话16621161987 2国内·那洪街区 ​,是,医院治疗不孕不育的专家联系电话国内那洪街区,"[医院, 治疗, 不孕, 不育, 的, 专家, 联系电话, 国内, 那洪, 街区]","[医院, 治疗, 不孕, 不育, 专家, 联系电话, 国内, 街区]"

In [725]:
data_2018["words_str"]=data_2018["words_clean"].apply(lambda x:" ".join(x))

In [726]:
#将文本中的词语转换为词频矩阵  
vectorizer = CountVectorizer()  
#计算个词语出现的次数  
X = vectorizer.fit_transform(data_2018["words_str"])  
#获取词袋中所有文本关键词  
word = vectorizer.get_feature_names()  
print (word)
#查看词频结果  
print(X.toarray())

['一万', '一万三千', '一万元', '一万次', '一下子', '一不小心', '一不留神', '一丝', '一两个', '一两天', '一两杯', '一两次', '一个个', '一个多月', '一个月', '一举', '一久', '一事', '一事无成', '一二十年', '一些第三', '一人', '一代', '一件', '一份', '一会', '一会儿', '一位', '一体', '一侧', '一儿', '一共', '一击', '一分钟', '一切正常', '一切顺利', '一到', '一刻', '一千', '一千多', '一半', '一半左右', '一双', '一取', '一口', '一口气', '一句', '一只', '一同', '一名', '一向', '一周', '一味', '一喷灵', '一回', '一团', '一圈', '一在', '一场', '一坐', '一块', '一堆', '一多囊', '一大', '一大堆', '一大早', '一套', '一女', '一子', '一孕', '一孩', '一定量', '一家', '一对', '一对一', '一对对', '一對雙', '一小', '一小部分', '一层', '一岁', '一年', '一年半载', '一年四季', '一度', '一张', '一微信', '一成不变', '一批', '一拖再拖', '一整天', '一文', '一方', '一无所获', '一日', '一日三餐', '一早', '一是', '一晒锦泰', '一月', '一有', '一朵', '一村', '一条', '一杨', '一杯', '一枚', '一架', '一查', '一根', '一棵树上吊死', '一次性', '一次次', '一步', '一步一个脚印', '一步到位', '一步步', '一段', '一段时间', '一水', '一波', '一波用', '一派', '一流', '一测', '一滴水', '一点', '一点很多', '一点点', '一父', '一环', '一班', '一生', '一男一女', '一百多万', '一百多个', '一盒', '一盘', '一看', '一知半解', '一种', '一站', '一端', '一竿子', '一笔', '一篇', '一类', '一粒', '一精卵', '一系列', '一级', '一线', '一线生机', '一组', '一聊', '一胎', '一脸', '一脸茫然', '一般来说', '一般而言', '一般说来', '一艾宝来', '一见钟情', '一言不合', '一试', '一说', '一路', '一辈', '一辈子', '一连', '一道', '一部', '一部分', '一针', '一长', '一门', '一问', '一阵', '一院', '一项', '一颗', '丁丁', '丁克', '丁香', '七个', '七八个', '七八次', '七千块', '七夕', '七年', '七斤', '七盒', '七窍生烟', '万不得已', '万个', '万事万物', '万事大吉', '万例', '万分', '万即', '万名', '万家', '万左右', '万年青', '万次', '万物', '万科', '万能', '万般无奈', '万艾可', '丈夫', '三个', '三五年', '三人', '三代', '三体', '三分之一', '三分之二', '三匡', '三十万', '三十五岁', '三十几岁', '三十几年', '三十多', '三十多年', '三口', '三合', '三四年', '三大', '三天', '三如', '三姑六婆', '三宝', '三家', '三年', '三思', '三是', '三月初', '三次', '三步', '三河', '三点', '三甲', '三盒', '三看', '三种', '三线', '三维', '三美泰', '三者', '三胎', '三胞胎', '三要素', '三角型', '三角形', '三镜', '三阴交', '三项', '三餐', '上举', '上会', '上传', '上冲', '上午', '上半年', '上受', '上周', '上唇', '上天', '上孕', '上学', '上宜', '上将', '上岗', '上市', '上常', '上床睡觉', '上当', '上心', '上放', '上次', '上沙', '上火', '上环', '上班', '上皮', '上皮细胞', '上称', '上策', '上级', '上线', '上网', '上肉', '上能', '上腺', '上船', '上药', '上葆婴', '上行', '上要', '下一代', '下丘脑', '下丘腦', '下个', '下个月', '下值', '下午', '下半年', '下单', '下发', '下坠', '下垂', '下备', '下好孕', '下导丝', '下弱', '下意识', '下手', '下方', '下有', '下条', '下次', '下水', '下水道', '下游', '下滑', '下灸', '下班', '下用', '下眼睑', '下级', '下经', '下肢', '下腹', '下腹部', '下药', '下蛋', '下行', '下课', '下身', '下载', '下辈子', '下部', '下降', '下雪', '下鲜', '不一有', '不为人知', '不为过', '不争', '不争气', '不二', '不仅如此', '不以', '不传', '不住', '不佳', '不佳则', '不信', '不假', '不停', '不像', '不全', '不冻', '不净', '不准', '不减', '不利', '不利于', '不利因素', '不到', '不动', '不单单是', '不去', '不及', '不受', '不可思议', '不可或缺', '不可逆性', '不可逆转', '不可避免', '不吃', '不合理', '不同之处', '不同于', '不和食', '不固', '不圆', '不在乎', '不在少数', '不在意', '不均', '不坏', '不堪回首', '不壮', '不多', '不多不少', '不大如', '不太', '不太多', '不太好', '不太有', '不好', '不孕', '不孕症', '不完全性', '不宜', '不容忽视', '不对劲', '不小', '不尽相同', '不幸', '不循坏', '不必要', '不忘', '不思', '不想', '不愿', '不懈努力', '不敢相信', '不断完善', '不断进步', '不明', '不明不白', '不明智', '不易', '不来', '不正', '不洁', '不生', '不用', '不用说', '不由自主', '不畅', '不痒', '不痛', '不相上下', '不相容', '不知', '不知所措', '不破', '不确定性', '不稳', '不稳固', '不竭', '不算', '不管不顾', '不管怎么', '不耐烦', '不育', '不育症', '不肿', '不胜枚举', '不能到达', '不能自己', '不良', '不良嗜好', '不良影响', '不良情绪', '不行', '不要紧', '不见', '不见不散', '不见得', '不规则', '不解', '不言而喻', '不计其数', '不让', '不论是', '不该', '不调', '不贵', '不足为奇', '不足之处', '不足以', '不足者', '不过关', '不远', '不远万里', '不适', '不适感', '不透气', '不通', '不长', '不间断', '不难', '不雅', '不需', '不饱和', '不高', '与会', '专业', '专业人士', '专业性', '专业知识', '专利', '专家', '专家库', '专家建议', '专家门诊', '专属', '专治', '专注', '专用', '专科', '专科医生', '专科医院', '专著', '专题', '专题讲座', '且量', '世俗', '世家', '世界', '世界卫生组织', '世界各地', '世界性', '世纪', '世贸', '世间', '丘脑', '丙烯酰胺', '丙肝', '丙酮酸', '业内', '业务', '业已', '东东', '东北', '东北角', '东南', '东西', '东院', '丝带', '丝毫', '丝线', '丢失', '两三个', '两三天', '两不误', '两个', '两人', '两位', '两例', '两侧', '两分钟', '两到', '两包', '两千多年', '两名', '两周', '两地', '两大', '两大类', '两天', '两年', '两性', '两扇门', '两断', '两方', '两条', '两杯', '两桶', '两次', '两步', '两点', '两瓶', '两盒', '两种', '两端', '两精', '两组', '两腰', '两至', '两虚', '两道', '两项', '两颗', '严厉', '严密', '严峻', '严格管理', '严肃', '严要求', '严谨性', '严重不足', '严重危害', '严重后果', '严重威胁', '严重破坏', '严重者', '丧失', '个个', '个人化', '个人卫生', '个体', '个体化', '个体差异', '个性化', '个数', '中上', '中为', '中介机构', '中会', '中前', '中医', '中医中药', '中医医院', '中医学', '中医学院', '中医科', '中医药', '中医药大学', '中医院', '中午', '中华文明', '中可因', '中国', '中国科学院', '中坚力量', '中奖', '中奖率', '中好孕', '中射出', '中将', '中山', '中山大学', '中度', '中心', '中患', '中意', '中所含', '中抗', '中招', '中文', '中文名', '中文翻译', '中断', '中无烂', '中旬', '中暑', '中有', '中期', '中枢', '中枢性', '中枢神经', '中止', '中正', '中段', '中毒', '中洲', '中秋', '中种', '中等', '中约', '中线', '中能', '中若', '中英文', '中药', '中西', '中西医', '中西药', '中要', '中见', '中起', '中过', '中途', '中重度', '丰地', '丰收', '丰满', '丰盈', '临床', '临床实验', '临床经验', '临床表现', '临床试验', '临时', '临江', '临江镇', '临症', '临近', '临门', '临门一脚', '丸剂', '丹参', '丹麦', '为个', '为例', '为促', '为值', '为元', '为先', '为准', '为分', '为啥', '为备', '为天', '为弱', '为强', '为形', '为时不晚', '为期', '为次', '为治', '为生', '为重', '为长', '主人', '主任', '主任医师', '主动', '主客观', '主持', '主治', '主治医师', '主治医生', '主流', '主稠厚', '主管', '主要症状', '主观原因', '主观因素', '主诊', '主题', '主食', '举例', '举例说明', '举列', '举办', '久久', '久坐', '久备', '久治', '久治不愈', '久病', '义诊', '之三', '之下', '之中', '之二', '之五', '之低', '之余', '之六', '之内', '之分', '之别', '之功', '之外', '之多', '之大', '之宗梨性', '之家', '之弊', '之情', '之效', '之旅', '之时', '之本', '之桥', '之气', '之源', '之神', '之称', '之缘', '之苦', '之言要', '之词', '之路', '之间', '之际', '乏力', '乐山', '乐昌', '乐观', '乐趣', '乖乖', '乘以', '乙型肝炎', '乙烯', '乙肝', '乙肝病毒', '乙酰', '九九八十一', '九吉公', '九吉公备', '九大', '九鼎', '也容', '也许', '习惯', '习惯性', '书摘', '书籍', '书记', '买单', '买药', '乱七八糟', '乱补', '乳房', '乳汁', '乳液', '乳白色', '乳腺', '乳腺癌', '乳酪', '乳酸', '争先恐后', '争吵', '争相', '争论', '事业', '事业型', '事业心', '事事', '事件', '事倍功半', '事儿', '事先', '事关', '事前', '事半功倍', '事取', '事后', '事宜', '事实', '事实上', '事态', '事情', '事是', '事真', '事花', '事要', '事项', '二三个', '二三十岁', '二两', '二个', '二人', '二代', '二分之一', '二十一', '二十五岁', '二十几岁', '二十年', '二卵胞', '二城', '二多囊', '二大', '二姐', '二孩', '二宝', '二宝妈', '二宝来', '二宝能', '二度', '二手烟', '二是', '二次', '二母', '二氧化碳', '二瓶', '二甲', '二看', '二维码', '二者', '二聚体', '二胎', '二超', '二配', '于单', '于天', '于宫', '于心', '于未然', '于胞', '亏损', '亏气', '亏虚', '亏血则', '云南', '云浮', '云集', '互动', '互粉', '互结', '互联网', '五个', '五倍', '五六', '五六天', '五六年', '五味子', '五大', '五大类', '五天', '五审', '五年', '五折', '五星', '五星级', '五月', '五月份', '五灵脂', '五类', '五罐', '五色', '五行', '五角场', '五谷杂粮', '五雷轰顶', '五项', '五颗', '亚丽怀', '亚健康', '亚泰', '亚洲', '亚甲减', '亚硝酸盐', '亢进', '交叉感染', '交感神经', '交换', '交换机', '交替', '交流', '交流会', '交点', '交给', '交通', '交通工具', '交通广播', '亦可', '亦然', '产下', '产做', '产前诊断', '产卵', '产卵期', '产后', '产品', '产地', '产妇', '产权', '产检', '产检时', '产物', '产程', '产道', '产量', '享乐', '享受', '享受性', '亮点', '亲临', '亲人', '亲们', '亲友们', '亲密', '亲情', '亲戚', '亲戚朋友', '亲民', '亲爱', '亲诊', '亲身经历', '亲近', '亲骨肉', '亳州', '人为', '人事', '人会', '人体', '人体器官', '人儿', '人参', '人口', '人口统计', '人员', '人命', '人因', '人士', '人备', '人大', '人工', '人工干预', '人工授精', '人工控制', '人工智能', '人工流产', '人常', '人慢', '人所处', '人才', '人数', '人母', '人民日报', '人流', '人满为患', '人生', '人生目标', '人省卫', '人类', '人类文明', '人美', '人群', '人花', '人问', '亿个', '亿左右', '亿计', '仅为', '仅次于', '仅能', '今天上午', '今天下午', '今日', '今明两天', '今晚', '介休', '介入', '介意', '介绍', '介质', '仍停留', '仍能生', '从业人员', '从业者', '从何下手', '从刚', '从前', '从备', '从外', '从头再来', '从孕', '从宝妈', '从容', '从小到大', '从小孔', '从岁', '从来不', '从根本上', '从超', '从这一点', '仓库', '仔细', '仔细检查', '他俩', '他克莫司', '付出', '付药', '仙女', '仙女们', '仙茅', '代价', '代偿', '代孕', '代母', '代理', '代表', '代言', '代谢', '代谢性', '代谢物', '令人', '令人敬畏', '以上者', '以下几点', '以人为本', '以内', '以化', '以备', '以天', '以往', '以抗', '以此', '以水为', '以瘀', '以示', '以肝为', '以致于', '以血为', '以资', '以防', '仪器', '仪器设备', '仪式', '仪微', '仪送', '价值', '价格', '任何一方', '任何人', '任性', '任意', '份伴', '份量', '企业', '伊芙嘉', '伊芙嘉助孕', '伊芙嘉能', '伍用', '休假', '休克', '休养', '休息', '休息天', '休息时间', '休整', '休眠状态', '休闲', '众多', '众所周知', '优于', '优先', '优先选择', '优劣', '优势', '优化', '优孕', '优惠', '优洲', '优点', '优生', '优生优育', '优甲乐', '优秀', '优育', '优胜劣汰', '优良', '优质', '优越性', '伙伴', '会为', '会儿', '会先', '会变', '会合', '会员卡', '会因', '会堂', '会多', '会少', '会得', '会时常', '会用', '会薄', '会要', '会诊', '会越', '会长', '会高', '伞端', '伞部', '传出', '传女', '传好', '传宗接代', '传导', '传承', '传播', '传来', '传染性', '传男不传', '传给', '传统', '传统观念', '传达', '传递', '传递窗', '伤到', '伤卵', '伤口', '伤害', '伤心', '伤疤', '伤痛', '伤身', '伪劣', '伯克利大学', '估计', '伴侣', '伴有', '伴随', '伸入', '似是而非', '但久备', '但会', '但压', '但天', '但恒健', '但量', '位于', '位列', '位移', '位精卵', '位置', '低下', '低且', '低于', '低于正常', '低会', '低值', '低到', '低多囊', '低少', '低有', '低水平', '低温', '低等', '低糖', '低聚', '低落', '低要', '低该', '低质量', '住在一起', '住宅', '住宿', '住手', '住院', '住院部', '佐以', '佐剂', '体会', '体内', '体力', '体力劳动', '体力活', '体后', '体型', '体外', '体外受精', '体寒', '体尾', '体弱多病', '体征', '体态', '体格', '体格检查', '体检', '体检中心', '体毛', '体温', '体温表', '体现', '体积', '体积小', '体系', '体细胞', '体育', '体育运动', '体育锻炼', '体育馆', '体谅', '体质', '体贴', '体部', '体重', '体重减轻', '体重增加', '体验', '体魄', '何为', '何嘉文', '何在', '何故', '何种', '何等', '何苦来哉', '余下', '余年', '余额', '佛陀', '作出', '作家', '作怪', '作息', '作息时间', '作用', '作祟', '你备', '你好', '佩戴', '佳节', '佳茵会', '佳茵助孕', '使命', '使断', '使树', '使用不当', '使用率', '使眼', '使者', '侄女', '例假', '例区', '例外', '例子', '例获', '供卵', '供卵供', '供应', '供给', '供血', '供选择', '依旧', '依次', '依法', '依然', '侥幸', '侥幸心理', '侦测', '侧向', '侧壁', '侧面', '侵害', '侵犯', '便会', '便宜', '便捷', '便携', '便是', '便秘', '便血', '促使', '促卵', '促性素', '促性腺激', '促排', '促排卵', '促进作用', '促销', '促黄体素', '俗称', '俗话说', '俗语说', '保不住', '保住', '保健', '保健作用', '保健品', '保健院', '保健食品', '保养', '保卫', '保卫战', '保存', '保存起来', '保守', '保宫术', '保密', '保得住', '保护', '保护性', '保护措施', '保持良好', '保持身材', '保温箱', '保湿', '保留', '保肝', '保胎', '保证', '保证供给', '保障', '保驾护航', '信不信', '信任', '信则', '信号', '信心', '信心十足', '信念', '信息', '信息学', '信报', '信誓', '信赖', '修养', '修复', '修整', '修理', '修身', '俱乐部', '俱佳', '倍增', '倍韻', '倒下', '倒位', '倒数', '倒流', '倒计时', '倒转', '候诊', '借助', '借着', '倡导', '值不值得', '值会', '值得', '值此', '倾向', '倾家荡产', '倾诉', '假卵', '假备', '假性', '假日', '假期', '假象', '偏于', '偏低', '偏向', '偏多', '偏大', '偏大卵', '偏大而', '偏寒', '偏少', '偏强', '偏方', '偏热且', '偏爱', '偏瘦', '偏盛', '偏碱', '偏薄', '偏见', '偏酸', '偏高', '偏高且', '偏高该', '做个', '做些', '做产前', '做人', '做人流', '做以', '做做', '做儿', '做冻', '做出', '做助孕', '做取', '做备', '做好', '做客', '做宫', '做手术', '做术', '做法', '做点', '做血', '做超', '做足', '做过', '做饭', '停下来', '停不下来', '停堪', '停天霞', '停孕', '停手', '停掉', '停歇', '停止', '停滞', '停留', '停留时间', '停经', '停者', '停育', '停药', '停越', '停车场', '停过', '健全', '健壮', '健康', '健康人', '健康成长', '健康报', '健康检查', '健康状况', '健忘', '健忘症', '健肾', '健脑', '健脾', '健身', '偶发性', '偶有', '偶然', '偷偷', '偷走', '傍晚', '储备', '储存', '催乳', '催乳素', '催产素', '催生', '傻傻', '像是', '僵硬', '儿女', '儿媳', '儿子', '儿有', '儿科', '儿童', '儿童哮喘', '儿约', '儿能', '儿茶素', '元凶', '元旦', '元次', '元素', '兄弟', '充值', '充分准备', '充分利用', '充分发挥', '充分考虑', '充实', '充当', '充沛', '充满', '充满希望', '充盈', '充血', '充足', '兆赫', '先兆', '先决条件', '先前', '先取', '先天', '先天不足', '先天性', '先扎', '先找', '先替', '先查', '先测', '先用', '先看', '先行', '先说', '先调', '先进', '先进设备', '先锋', '光临', '光彩', '光泽', '光点', '光片', '光荣', '光辉', '光镜', '克星', '克服', '克氏', '克水', '克生', '克醋', '克隆技术', '免不了', '免疫', '免疫力', '免疫学', '免疫性', '免疫抑制', '免疫抗体', '免疫治疗', '免疫系统', '免疫耐受', '免费', '免除', '兑现', '兔唇', '党支部', '入住', '入侵', '入侵者', '入口', '入手', '入群', '入院', '入驻', '內膜', '全世界', '全国', '全场', '全套', '全如', '全家', '全对', '全攻略', '全新', '全方位', '全是', '全球', '全球化', '全科', '全称', '全程', '全素', '全组', '全美', '全者', '全脂', '全脑', '全脸', '全身', '全身性', '全身检查', '全过程', '全部都是', '全长', '全长约', '全面提高', '全面落实', '全面解决', '全麻', '八倍', '八十', '八盒', '公主', '公众', '公众号', '公分', '公号', '公司', '公婆', '公寓', '公平', '公开', '公民权', '公益', '公立医院', '公认', '六一', '六七十', '六个', '六个月', '六個', '六分之一', '六千块', '六大', '六天', '六年', '六成', '六斤', '六级', '六胜', '六项', '兰岭园', '共乐', '共同努力', '共同爱好', '共奏', '共青团', '关乎', '关元', '关切', '关心', '关成败', '关注', '关爱', '关系', '关系密切', '关联', '关键', '关键作用', '关键因素', '关键性', '关键时期', '关键期', '关键步骤', '关键点', '关键环节', '关闭', '兴奋', '兴趣', '兴趣爱好', '兴隆', '兵力', '其内', '其华在面', '其实不然', '其患', '其所含', '其是', '其来', '其病', '其系膜', '其间', '具体内容', '具体情况', '具体操作', '具体方法', '具体表现', '具备', '典型', '养儿育', '养出', '养分', '养卵', '养囊', '养囊率', '养在', '养好', '养娃', '养小', '养成', '养护', '养料', '养森', '养生', '养生术', '养精个', '养精蓄锐', '养肝', '养肝脑', '养育', '养血', '养鱼', '兼任', '兼得', '兼顾', '内会', '内使', '内侧', '内冻', '内分泌', '内分泌腺', '内到', '内助', '内单', '内口', '内向', '内在', '内外', '内容', '内层', '内异症', '内张力', '内心', '内才', '内易', '内有', '内核', '内游到', '内皮细胞', '内科', '内脏', '内脏器官', '内膜', '内若', '内蒙古', '内行', '内衣', '内裤', '内诊', '内近', '内部', '内镜', '再三', '再也', '再予', '再备', '再就是', '再度', '再怀', '再接', '再显', '再晚', '再次发生', '再添', '再生', '再留', '再行', '再通', '再造', '再障', '冒险', '农历', '农场', '农村', '农村妇女', '农药', '冠军', '冠周', '冠周炎', '冠心病', '冠状动脉', '冥想', '冬天', '冬病', '冬眠', '冬至', '冯云', '冯宗文', '冰冷', '冰块', '冰山一角', '冰心', '冰瓷', '冰箱', '冰饮要', '冲凉', '冲击', '冲刷', '冲刺', '冲动', '冲洗', '冲淡', '冲破', '冲突', '决心', '决策', '决胜', '决裂', '冷冻', '冷存', '冷热水', '冷畏寒', '冷藏', '冷藏室', '冷言冷语', '冷链', '冷风吹', '冷饮', '冻卵', '冻存', '冻结', '冻龄密', '净化器', '准以', '准入', '准则', '准备就绪', '准妈咪', '准妈妈', '准孕', '准字', '准字号', '准时', '准确', '准确性', '准确率', '凉凉', '凉性', '凉拌', '凉爽', '凋亡', '凌晨', '减低', '减半', '减压', '减小', '减少', '减弱', '减慢', '减或加', '减时', '减甲减', '减缓', '减胎', '减至', '减药', '减轻', '减轻负担', '减退', '减重', '减量', '凑好', '凝固', '凝结', '凝血', '凝血因子', '凝集', '几个', '几亿', '几分钟', '几副', '几十个', '几十天', '几十年', '几十项', '几千', '几千年', '几大', '几天', '几家', '几家愁', '几年', '几招', '几支', '几日', '几样', '几次', '几点', '几率', '几率比', '几百', '几百万个', '几百个', '几百例', '几种', '几类', '几项', '几颗', '凡有', '凯哥', '凯特', '凶手', '凹凸不平', '出世', '出力', '出动', '出厂', '出国', '出境', '出处', '出工', '出差', '出新', '出汗', '出炉', '出现异常', '出生', '出生年月', '出生率', '出血', '出血量', '出行', '出诊', '出谋划策', '出身', '出错', '出门', '出院', '刀手', '分不清楚', '分为', '分享', '分会', '分出', '分前', '分化', '分发', '分娩', '分子', '分工合作', '分布', '分开', '分成', '分手', '分散', '分析', '分析法', '分析表明', '分次', '分歧', '分泌', '分泌物', '分泌量', '分流', '分离', '分离出来', '分类', '分级', '分裂', '分解', '分身', '分辨', '分辨率', '分配', '分针', '分钟', '切切实实', '切口', '切实可行', '切开', '切开术', '切忌', '切掉', '切片', '切记', '切除', '切除术', '划上', '划分', '划算', '列入', '列出', '列着', '刘云鹏', '刘凯', '刘国忠', '刘女士', '刘姗', '刘敬圆', '刘晓庆', '刘颖', '刚刚', '刚备', '刚测', '创业', '创伤', '创伤性', '创到', '创办', '创始人', '创建', '创性', '创新', '创造', '创造条件', '创面', '初婚', '初心', '初期', '初次', '初步', '初潮', '初胎', '初诊', '判别', '判定', '判断', '利于', '利尿', '利弊', '利是', '利水', '利用', '利益', '利眠宁', '别傻了', '别去', '别墅', '别太过', '别忘了', '别忙', '别来无恙', '别着急', '别老', '别错过', '刮匙', '刮宫', '刮术', '刮来', '刮片', '刮起', '刮风下雨', '到来', '到极点', '到葆婴', '到达', '到院', '制作', '制作方法', '制剂', '制动', '制品', '制定', '制度', '制法', '制约', '制订', '制造', '刺激', '刺激性', '刺激素', '刻意', '刻意追求', '刻起', '刻骨铭心', '剂个', '剂量', '削弱', '削薄', '前一天', '前三天', '前两天', '前个', '前任', '前会', '前体', '前兆', '前先', '前几日', '前列腺', '前列腺炎', '前列腺素', '前功尽弃', '前取', '前天', '前年', '前应', '前往', '前所未有', '前拔', '前排', '前提', '前提条件', '前方', '前景', '前有', '前期', '前术', '前来', '前沿', '前男友', '前症', '前程似锦', '前置', '前行', '前要', '剔掉', '剔除', '剖宫产', '剖析', '剖腹产', '剥离', '剥脱', '剥落', '剧烈', '剧烈运动', '剧痛', '剩下', '剩余', '副作用', '副性征', '創手術', '力低', '力度', '力气', '力量', '劝解', '劝说', '办事', '办公', '办公室', '办卡', '办法', '功劳', '功恒健', '功效', '功用', '功能', '功能主治', '功能性', '功能障碍', '功课', '加压素', '加大', '加川', '加川柏', '加弱', '加强锻炼', '加彩', '加微信', '加快', '加拿大', '加油', '加深', '加湿器', '加班', '加用', '加盟', '加胖', '加至', '加芯', '加重', '加量', '加长', '加龟胶', '务工', '务必', '劣汰', '劣质', '动一动', '动作', '动力', '动力学', '动态', '动物', '动物性', '动物类', '动用', '动能', '动脉硬化', '动赴', '动静', '助于', '助其', '助力', '助好孕', '助孕', '助孕侠', '助孕取', '助孕园', '助孕定', '助孕率', '助孕生', '助孕神', '助孕者', '助孕要', '助孕谨', '助您', '助手', '助阳', '助阳固', '努力', '劳动', '劳累', '劳苦功高', '劳逸结合', '势不可挡', '势头', '势必', '势必会', '勃起', '勃锐', '勇往直前', '勇敢', '勇气', '勉为其难', '勉强', '募集', '勤快', '勤换', '包养', '包含', '包块', '包头', '包容', '包括', '包是', '包皮', '包膜', '包裹', '化合物', '化名', '化多囊', '化妆棉', '化学', '化学治疗', '化学法', '化学物质', '化学药品', '化对', '化工厂', '化工原料', '化明', '化未', '化疗', '化等', '化解', '化验', '化验单', '北上', '北路', '北部', '匹敌', '区分', '区別', '区别', '区微', '医保', '医务', '医务人员', '医嘱', '医声', '医学', '医学专业', '医学专家', '医学中心', '医学会', '医学博士', '医学界', '医对', '医师', '医年', '医德', '医患', '医护', '医护人员', '医方', '医治', '医生', '医疗', '医疗保健', '医疗保障', '医疗机构', '医药', '医院', '医馆', '十一', '十一点', '十三岁', '十个月', '十二生肖', '十几', '十几万', '十几个', '十几年', '十分之一', '十周年', '十多天', '十大', '十天', '十年', '十月', '十来天', '十盒', '十种', '十答', '十问', '千万别', '千万家', '千元', '千克', '千思万想', '千方百计', '千次', '千辛万苦', '千金', '升级', '升至', '升高', '午休', '半个', '半信半疑', '半倍', '半只', '半夜', '半天', '半女', '半小时', '半年', '半月', '半胱氨酸', '华丽', '华人', '华裔', '华西', '华西都市报', '协会', '协助', '协同', '协和', '协和医院', '协议', '协调', '卓哥', '单一', '单个', '单从', '单位', '单体', '单侧', '单单是', '单卵', '单向', '单味', '单囊', '单据', '单方', '单方面', '单条', '单次', '单测', '单独', '单细胞', '单胎', '单角', '单身', '单颗', '卖宁密康', '卖药', '南山区', '南平', '南方', '南湖', '南瓜籽', '博士', '博士后', '博客', '博鳌', '占成', '占据', '占有', '卡买', '卡路里', '卢羿', '卧具', '卧室', '卧床', '卧房', '卫生', '卫生保健', '卫生局', '卫生巾', '卫生棉', '卫生部', '印度', '印象', '危及', '危害', '危害性', '危机', '危险', '危险性', '危险期', '即会', '即先', '即单', '即卵胞', '即可', '即将来临', '即易', '即用', '却不曾', '却会', '却成', '却是', '却治', '却说', '卵丘', '卵个', '卵前', '卵取', '卵圆形', '卵子', '卵室', '卵巢', '卵巢功能', '卵巢囊肿', '卵巢癌', '卵数', '卵日', '卵母细胞', '卵泡', '卵管', '卵细胞', '卵胞', '卵裂', '卷尾', '卷鹅', '厂家', '历史', '历史舞台', '历程', '历经', '历险记', '厉害', '压力', '压在', '压强', '压抑', '压根', '压箱', '压迫', '厌恶', '厌食', '厌食症', '厕所', '厘米', '厚味', '厚度', '厚膜', '厚薄', '厚重', '原以为', '原件', '原位杂交', '原先', '原则', '原则上', '原创', '原发', '原发性', '原因', '原始', '原文', '原料', '原有', '原本', '原核', '原理', '厦门', '厲害', '去年', '去掉', '去除', '参与', '参加', '参数', '参考', '参考价值', '参考值', '参观', '又生', '又称', '及大', '及排', '及早', '及早准备', '及时发现', '及时处理', '及次', '及白藜', '及种', '及血类', '及超', '及过', '及重', '及骶部', '友爱', '双亲', '双侧', '双全', '双发', '双合', '双向', '双喜', '双喜临门', '双头', '双子宫', '双尾', '双手', '双旦', '双目', '双相', '双眼', '双胎', '双胞胎', '双节', '双虾', '双角', '双赢', '双重', '反反复复', '反复', '反差', '反常', '反应迟钝', '反正', '反要', '反观', '反馈', '发作', '发出', '发动机', '发展', '发展中国家', '发抖', '发挥', '发挥作用', '发改委', '发明', '发来', '发炎', '发烧', '发热', '发现', '发现异常', '发现自己', '发生', '发生变化', '发生率', '发病', '发病率', '发给', '发育', '发育不全', '发育不良', '发育畸形', '发胀', '发胖', '发芽', '发菜', '发表', '发表文章', '发觉', '发言权', '发质', '发达', '发达国家', '发迹', '发送', '发青', '发黄', '发黑', '取代', '取决', '取决于', '取出', '取到', '取卵', '取卵少', '取卵数', '取卵术', '取卵针', '取号', '取完', '取得成功', '取得联系', '取样', '取消', '取环', '取环后', '取环备', '取精', '取精前', '取精后', '取精室', '取精术', '取精者', '取而代之', '取肘', '取舍', '取药', '取适量', '受众', '受伤', '受体', '受到破坏', '受到限制', '受力', '受备', '受孕', '受孕率', '受害人', '受容', '受寒', '受尽', '受损', '受术者', '受欢迎', '受益', '受益人', '受益者', '受精', '受精卵', '受精率', '受苦', '受血及', '受过', '受邀', '受阻', '受限', '受限制', '变凉', '变化', '变厚', '变多', '变大', '变大变', '变好', '变小', '变少', '变差', '变干变', '变异', '变异型', '变弱', '变形', '变得', '变心', '变性', '变性手术', '变硬', '变窄', '变美', '变荒', '变薄', '变越', '变通', '变量', '变黄有', '叙述', '口唇', '口服', '口服药物', '口碑', '口罩', '口腔', '口腔疾病', '口臭', '口里', '口风', '口饭', '古农', '古往今来', '古汉', '另一端', '另有打算', '叩齿', '只不过', '只为', '只会', '只传', '只差', '只服', '只用', '只能', '只靠线', '叫嚷', '叫声', '叫好', '叫易孕', '叮咛', '叮嘱', '可不可以', '可不是', '可为', '可人儿', '可供', '可信', '可先', '可冻存', '可到', '可加', '可加用', '可取', '可口', '可可', '可喜可贺', '可在度', '可循', '可怕', '可怜', '可恋', '可恒健', '可惜', '可想而知', '可抑制', '可控因素', '可有', '可爱', '可的松', '可知', '可移植', '可能性', '可致', '可行', '可行性', '可观', '可谓', '可达', '可达天', '可达岁', '可逆', '可逆性', '可选', '可靠', '可高达', '台上', '台阶', '台面', '台风', '史且', '史无前例', '史来', '史核', '史樱', '史者', '右侧', '右側', '叶绿素', '叶酸', '叶酸片', '叶面积', '号召', '号源', '号码', '号键', '司令部', '司机', '吃些', '吃住行', '吃剂', '吃喝玩乐', '吃备', '吃太多', '吃尽苦头', '吃惊', '吃掉', '吃放', '吃梨要', '吃水果', '吃法', '吃燕', '吃益', '吃素', '吃药', '吃货', '吃零食', '吃饭', '吃饺子', '各不相同', '各位朋友', '各国', '各大', '各家', '各异', '各式各样', '各方', '各有', '各有不同', '各种各样', '各种因素', '各类', '各缝', '各若', '各若大', '各身', '各项', '合不拢', '合作', '合作伙伴', '合同', '合并', '合并症', '合影', '合征', '合恒健适', '合成', '合拢', '合格', '合欢花', '合法', '合法性', '合适', '吉林省', '吉浦', '吉祥', '同一个', '同一天', '同事', '同仁', '同位素', '同厂', '同号', '同城会', '同居', '同性', '同感', '同房', '同查', '同步', '同步化', '同步性', '同步进行', '同治', '同济', '同种', '同等', '同类', '同胞', '同胞们', '同行', '同诊', '名人', '名医', '名媛', '名字', '名老', '名额', '名额有限', '后下', '后个', '后代', '后以', '后会', '后会变', '后准', '后取', '后台', '后后', '后周', '后备', '后天', '后天性', '后孕九周', '后岁', '后峡部', '后常较', '后应', '后开', '后张', '后悔', '后悔药', '后悔莫及', '后患', '后援团', '后易', '后期', '后果', '后盾', '后经', '后续', '后腰', '后要', '后过', '后进', '后远', '后遗症', '后顾之忧', '吐出来', '吐血', '向上', '向前', '向外', '吓一跳', '吕群', '吞咽', '吞噬', '吞津养', '吠陀', '否定', '否认', '含有', '含氧量', '含硫', '含种', '含量', '含锌', '含锌量', '听书涨', '听从', '听到', '听力', '听取', '听得', '听点', '听见', '听觉', '听诊', '听诊器', '听话', '听说', '听课', '听闻', '启动', '吸入', '吸到', '吸取', '吸引', '吸收', '吸烟', '吸管', '吸起', '吸进', '吸附', '吻合', '吻合术', '呈上升', '呈圆形', '呈条', '呈现', '呈酸性', '告别', '告知', '告示', '告终', '告诉', '告诫', '呕吐', '周一', '周三', '周为', '周五', '周六', '周内', '周到', '周前', '周后', '周岁', '周年', '周应', '周慧敏', '周敏', '周教授', '周时', '周期', '周期性', '周期短', '周末', '周用', '周而复始', '周边', '味儿', '味精', '味苦', '味道', '呵护', '呼吸', '呼吸系统', '呼吸道', '命主', '命名', '命格', '命火', '命理', '命运', '咀嚼', '咋办', '咋整', '和准', '和谐', '咖们', '咖啡', '咖啡因', '咖啡色', '咨询', '咨询中心', '咨询服务', '咨询电话', '咬合', '咱能', '咳嗽', '咸过', '品德', '品牌', '品种', '品质', '哥本哈根大学', '哪一块', '哪些因素', '哪些方面', '哪些项目', '哪几个', '哪几天', '哪几种', '哪家', '哪种', '哪类', '哺乳动物', '哺乳期', '唇腭裂', '唐氏', '唐氏儿', '唤醒', '唯一', '唾液', '商业', '商品房', '商场', '商城', '商榷', '商都', '商量', '商量一下', '商铺', '啊啊啊', '啤酒肚', '啮齿动物', '啮齿类动物', '善于', '善复', '喘息', '喜事', '喜孕', '喜岁', '喜得', '喜悦', '喜报', '喜欢', '喜气', '喜洋洋', '喜相逢', '喜笑颜开', '喜糖', '喜获', '喜蛋', '喜讯', '喝一杯', '喝了酒', '喝出', '喝有', '喝水', '喝点', '喝牛奶', '喝粉', '喝角豆', '喝酒', '喪失', '喷剂', '嗜好', '嗜睡', '嘟嘟', '嘱

In [727]:
#词的维度
print(len(word))

11474

In [728]:
#文本表述维度
X.toarray().shape

(1602, 11474)

In [729]:
#类调用  
transformer = TfidfTransformer()  
#将词频矩阵X统计成TF-IDF值  
tfidf = transformer.fit_transform(X)  
#查看数据结构 tfidf[i][j]表示i类文本中的tf-idf权重  
print(tfidf.toarray()  )

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

In [730]:
#查看第一个文本的词的tfidf值
for i in tfidf.toarray()[0]:
    if i!=0:
        print(i)

0.2452292301017844
0.1808819890312192
0.1443937027621794
0.1664420271640152
0.18997764335496417
0.18268119995739526
0.2239229493634262
0.23055351905217888
0.10233053527585158
0.2672303050371393
0.119097364200075
0.13787971785566366
0.2383426461514016
0.2209435544637982
0.1401830303350684
0.1319985522805218
0.5748449081191365
0.3124229348092836

In [734]:
k=3

In [735]:
#LDA主题建模
#设置主题数量，学习方式，超参数α，β取默认值。
lda = LatentDirichletAllocation(n_components=k, learning_method='batch', max_iter=50, random_state=3)
lda_topics = lda.fit_transform(tfidf.toarray())

In [736]:
#对主题词做降序排列
sorting = np.argsort(lda.components_, axis=1)[:, ::-1]
feature_names = np.array(vectorizer.get_feature_names())

mglearn.tools.print_topics(topics=range(k), feature_names=feature_names,
                           sorting=sorting, topics_per_chunk=5, n_words=20)

topic 0       topic 1       topic 2
--------      --------      --------
预约            主任            试管婴儿
国内            怀孕            国外
优惠            医院            不孕
意想不到          恭喜            医院
公众号           报喜            女性
街区            医生            试管
教授            输卵管           子宫
宝典            调理            不育
最全            宝宝            精子
门诊            国内            胚胎
关注            怀上            检查
会诊            妇产医院          怀孕
联系电话          就诊            国内
号码            成功            输卵管
身份证           中西医           影响
抓紧时间          治疗            卵巢
妇产医院          好孕            治疗
老店            艾灸            内膜
东院            腹腔镜           移植
同号            确诊            原因

In [602]:
for k in range(3,7):
    print("============"+str(k)+"============")
    #LDA主题建模
    #设置主题数量，学习方式，超参数α，β取默认值。
    lda = LatentDirichletAllocation(n_components=k, learning_method='batch', max_iter=50, random_state=0)
    lda_topics = lda.fit_transform(tfidf.toarray())
    #对主题词做降序排列
    sorting = np.argsort(lda.components_, axis=1)[:, ::-1]
    feature_names = np.array(vectorizer.get_feature_names())

    mglearn.tools.print_topics(topics=range(k), feature_names=feature_names,
                               sorting=sorting, topics_per_chunk=5, n_words=20)

============3============
topic 0       topic 1       topic 2
--------      --------      --------
爸爸            试管婴儿          医院
缩阴            国外            主任
艾灸            不孕            国内
懷上            医院            医生
男寶寶           女性            怀孕
高峰论坛          试管            恭喜
想当            子宫            报喜
老婆            不育            调理
卧室            精子            宝宝
生二胎           胚胎            输卵管
准备就绪          怀孕            怀上
具体表现          检查            就诊
忌讳            输卵管           预约
感动            影响            国际
听说            卵巢            妇产医院
饮料            治疗            成功
两盒            内膜            中西医
动力            移植            治疗
老公            国内            生殖
喜悦            原因            好孕


============4============
topic 0       topic 1       topic 2       topic 3
--------      --------      --------      --------
预约            试管婴儿          凝胶            有何
优惠            国外            妇科            偏爱
意想不到          医院            用后            公司
公众            不孕            大不大           生二胎
宝典            怀孕            官方            卧室
最全            国内            爱沐私护          睡姿
教授            输卵管           周知            具体表现
会诊            女性            解读            隐匿
门诊            不育            大姨妈           养精蓄锐
号码            试管            微商            突破
身份证           子宫            无孕            大宝
关注            检查            微信            女郎
东院            医生            摩丝            过客
病例            精子            不痒            伤心
人民            胚胎            假卵            深层次
小护            治疗            睡得            捣鬼
高峰论坛          卵巢            积液            五类
贴心            影响            喜得            闺蜜
语音            内膜            高能            瞧瞧
抓紧时间          成功            不信            封闭性


============5============
topic 0       topic 1       topic 2       topic 3       topic 4
--------      --------      --------      --------      --------
预约            试管婴儿          妇科            贝贝            权威专家
国内            国外            凝胶            思家            国际
人民            医院            摩丝            解读            团队
优惠            不孕            姐姐            日历            大力支持
意想不到          怀孕            私密            客户            合作伙伴
公众            输卵管           官方            代母            战略
会诊            女性            用后            翻译            国门
关注            不育            微信            偏爱            顶端
免费            国内            卵巢囊肿          生二胎           老师
这件            试管            糜烂            隐匿            联盟
缩阴            子宫            顾客            养精蓄锐          领航
门诊            检查            爱沐私护          备受            剖腹产
妇科医院          医生            舒芯宝           落幕            睡姿
宝典            精子            没用            喜悦            忌讳
最全            胚胎            小护            深层次           突破点
坐诊            治疗            贴心            捣鬼            苦瓜
征兆            卵巢            积液            五类            搞清
教授            影响            无孕            漫画            伙伴
获取            内膜            体检            两盒            大不大
号码            主任            超话            屏幕            留下


============6============
topic 0       topic 1       topic 2       topic 3       topic 4
--------      --------      --------      --------      --------
医院            试管婴儿          凝胶            主任            国际
国内            国外            妇科            怀孕            医学
预约            不孕            用后            医院            医疗
不育            女性            广西            恭喜            医院
医生            子宫            摩丝            报喜            国内
优惠            试管            官方            医生            生殖
意想不到          精子            医学中心          调理            不育
人民            胚胎            微信            怀上            权威专家
这件            医院            私密            输卵管           排行榜
关注            输卵管           首都医科大学        宝宝            不孕
公众            检查            顾客            成功            孕育
不孕            影响            专家库           国内            瘢痕
教授            不育            博士生           就诊            团队
正确            怀孕            评审            治疗            健康
备孕            卵巢            效果            中西医           联盟
科普            内膜            导师            妈妈            顶端
会诊            治疗            大宝            不孕            国门
门诊            移植            爱沐助孕          好孕            大力支持
专家            原因            圣洁            确诊            合作伙伴
中心            导致            睡得            妇产医院          战略


topic 5
--------
解读
下载
两盒
哪家
秘诀
漫画
客户
具体表现
隐患
中医
举列
体验
深层次
屏幕
科普
月亮
外国
妙招
封闭性
祛斑