In [565]:
import pandas as pd
import jieba
import re
import wordcloud
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer  
import numpy as np
from sklearn.feature_extraction.text import TfidfTransformer  
from sklearn.decomposition import PCA
import warnings
warnings.filterwarnings("ignore")
from sklearn.cluster import KMeans
from sklearn.decomposition import LatentDirichletAllocation
import mglearn

In [566]:
data_2023=pd.read_excel("./low_2023.xlsx")

In [567]:
data_2023.head()

,mid,日期,内容,转发数,评论数,点赞数,博主,来自,uid,是否已认证,认证内容
0,4985123764965953,2023-12-31 21:33,湛女士一直都很希望能够拥有自己的孩子，但是却发现自己并没有怀运的能力。因此，她决定做三代试管...,NaN,NaN,NaN,小怀妈妈送好孕,微博网页版,2199823755,False,NaN
1,4985095582126892,2023-12-31 19:41,苗女士在二十六岁的时候就开始出现一些怪异的身体现象。医生告诉她这是因为她的卵巢衰退了。这意味...,NaN,NaN,NaN,小怀妈妈送好孕,微博网页版,2199823755,False,NaN
2,4985054528799643,2023-12-31 16:58,如果是不孕不育的问题不太严重，可以先尝试在国内做第一代、第二代试管，如果失败了再考虑去俄罗斯...,NaN,NaN,NaN,胖爸爸美国试管婴儿上海,微博网页版,7677311178,True,海外团队，跨境试管生殖机构咨询顾问
3,4985052263875826,2023-12-31 16:49,南京女客人和先生毕业就结婚了，因为年轻没想着要孩子，结婚3年后，想要孩子结果备孕了两年一直没...,NaN,NaN,NaN,胖爸爸美国俄罗斯泰国试管婴儿,微博网页版,3340004800,True,海外专家团队 专注试管生殖领域 迎接新生传递爱
4,4985044102285640,2023-12-31 16:16,绝育复通术后，促排三个月，成功怀孕，每天都有好消息，快来点赞接好孕呀！#不孕不育##试管婴儿...,NaN,NaN,NaN,宝宝梦工场周红医生,微博视频号,1338696775,True,北京五洲妇儿医院生殖科主任，今日排行榜签约自媒体人 母婴育儿博主

In [568]:
data_2023.shape

(5842, 11)

In [569]:
data_2023=data_2023[["内容"]]

In [570]:
data_2023.head()

                                                  内容
0  湛女士一直都很希望能够拥有自己的孩子，但是却发现自己并没有怀运的能力。因此，她决定做三代试管...
1  苗女士在二十六岁的时候就开始出现一些怪异的身体现象。医生告诉她这是因为她的卵巢衰退了。这意味...
2  如果是不孕不育的问题不太严重，可以先尝试在国内做第一代、第二代试管，如果失败了再考虑去俄罗斯...
3  南京女客人和先生毕业就结婚了，因为年轻没想着要孩子，结婚3年后，想要孩子结果备孕了两年一直没...
4  绝育复通术后，促排三个月，成功怀孕，每天都有好消息，快来点赞接好孕呀！#不孕不育##试管婴儿...

In [571]:
data_2023=data_2023.drop_duplicates()

In [572]:
data_2023.head()

                                                  内容
0  湛女士一直都很希望能够拥有自己的孩子，但是却发现自己并没有怀运的能力。因此，她决定做三代试管...
1  苗女士在二十六岁的时候就开始出现一些怪异的身体现象。医生告诉她这是因为她的卵巢衰退了。这意味...
2  如果是不孕不育的问题不太严重，可以先尝试在国内做第一代、第二代试管，如果失败了再考虑去俄罗斯...
3  南京女客人和先生毕业就结婚了，因为年轻没想着要孩子，结婚3年后，想要孩子结果备孕了两年一直没...
4  绝育复通术后，促排三个月，成功怀孕，每天都有好消息，快来点赞接好孕呀！#不孕不育##试管婴儿...

In [573]:
def remove_hashtags(text):
    # 使用正则表达式匹配两个#之间的内容，并替换为空字符串
    cleaned_text = re.sub(r'#(.*?)#', '', text)
    return cleaned_text

In [574]:
#删除话题标志
data_2023["内容"]=data_2023["内容"].apply(lambda x:remove_hashtags(x))

In [575]:
#用大模型判断是否是不孕不育话题
import requests
def send_post(url,data):
    try:
        response = requests.post(url, json=data)
        if response.status_code == 200:
            #             print("POST request was successful!")
            #             print("Response data:")
            return response.json()
        else:
            print(f"POST request failed with status code: {response.status_code}")
    except requests.exceptions.RequestException as e:
        print(f"Error occurred: {e}")
url="http://180.76.49.225:7861/chat"

In [576]:
# realt_flag=[]

In [577]:
for cont in data_2023["内容"].values:
    data={"question":"请帮我判断以下文本是否关于不孕不育或者生育的话题，如果是，请直接输出一个字是，否则直接输出不是，务必不要返回其他内容。文本是："+cont}
    realt_flag.append(send_post(url,data)["answer"])

In [578]:
data_2023["relat"]=realt_flag

In [579]:
data_2023=data_2023[data_2023["relat"].apply(lambda x:x=="是")]

In [580]:
data_2023.to_excel("./2023_rel.xlsx")

In [581]:
data_2023.shape

(4708, 2)

In [582]:
#替换名称
cn_city=["四川省","四川","南岳","上海","广州","深圳","东莞","重庆","北京","合肥","郑州","天津","无锡","南宁","忻州","长沙","南宁",
         "南王","漕河镇","黄冈","湖南","十安","湖南","十安","南京","信阳","沈阳","台湾","汕头","广东","河北","郴州","邯郸","海口",
        "河南省","兰州","杭州","济南","冀南","京沪","抚州","石家庄","洛阳市","洛阳","长春"]
out_city=["法国","泰国","澳洲","乌克兰","曼谷","马来西亚","英国政府","美国","欧洲","阿德莱德","俄罗斯"]
person=["顾岩","田纪香","王丽敏","王铁梅","铁梅","庹有烈","匡淑杰","田平君","田平","医羽","爱问","张潇潇","李媛","崔娟","郑芬芬",
       "李颖","周薇","董曦","程玲","白舰波","斯托克"]
hospi=["怡康","九院","百佳","宝来佳运","恒健","济爱","宜正堂","卫人","仁和","北辰","朝阳医院","衍宗堂","和睦家","仁爱医院","华博",
      "红房子","天伦","谷方益","同济","望京","京科","桃清堂","谷医堂"]

In [583]:
def replace(ss):
    for c in cn_city:
        ss=ss.replace(c,"国内")
    for c in out_city:
        ss=ss.replace(c,"国外")
    for c in person:
        ss=ss.replace(c,"医生")
    for c in hospi:
        ss=ss.replace(c,"医院")
    return ss

In [584]:
data_2023["内容"]=data_2023["内容"].apply(lambda x:replace(x))

In [585]:
#只保留中文
data_2023["content2"]=data_2023["内容"].apply(lambda x:re.sub(r'[^\u4e00-\u9fa5]','',str(x)))

In [586]:
#结巴分词
data_2023["words"]=data_2023["content2"].apply(lambda x:jieba.lcut(x))

In [587]:
data_2023.head()

,内容,relat,content2,words
0,湛女士一直都很希望能够拥有自己的孩子，但是却发现自己并没有怀运的能力。因此，她决定做三代试管...,是,湛女士一直都很希望能够拥有自己的孩子但是却发现自己并没有怀运的能力因此她决定做三代试管试试不...,"[湛, 女士, 一直, 都, 很, 希望, 能够, 拥有, 自己, 的, 孩子, 但是, 却..."
1,苗女士在二十六岁的时候就开始出现一些怪异的身体现象。医生告诉她这是因为她的卵巢衰退了。这意味...,是,苗女士在二十六岁的时候就开始出现一些怪异的身体现象医生告诉她这是因为她的卵巢衰退了这意味着她...,"[苗, 女士, 在, 二十六岁, 的, 时候, 就, 开始, 出现, 一些, 怪异, 的, ..."
2,如果是不孕不育的问题不太严重，可以先尝试在国内做第一代、第二代试管，如果失败了再考虑去国外或...,是,如果是不孕不育的问题不太严重可以先尝试在国内做第一代第二代试管如果失败了再考虑去国外或者国外...,"[如果, 是, 不孕, 不育, 的, 问题, 不太, 严重, 可以, 先, 尝试, 在, 国..."
3,国内女客人和先生毕业就结婚了，因为年轻没想着要孩子，结婚3年后，想要孩子结果备孕了两年一直没...,是,国内女客人和先生毕业就结婚了因为年轻没想着要孩子结婚年后想要孩子结果备孕了两年一直没有成功喝...,"[国内, 女, 客人, 和, 先生, 毕业, 就, 结婚, 了, 因为, 年轻, 没, 想着..."
4,绝育复通术后，促排三个月，成功怀孕，每天都有好消息，快来点赞接好孕呀！ 2国内·国内五洲妇儿...,是,绝育复通术后促排三个月成功怀孕每天都有好消息快来点赞接好孕呀国内国内五洲妇儿医院宝宝梦工场周...,"[绝育, 复通, 术后, 促排, 三个, 月, 成功, 怀孕, 每天, 都, 有, 好消息,..."

In [620]:
#读停用词
StopDictionary_path = './stop_words.txt'
stop_words = []

In [621]:
# 加载停用词
def get_stopwords(filePath):
    global stop_words
    f = open(filePath, 'r', encoding='utf8', errors='ignore')
    line = f.readline()
    while line:
        stop_words.append(line.strip())
        line = f.readline()
    f.close()

In [622]:
get_stopwords(StopDictionary_path)

In [623]:
#去掉数据中的停用词
def drop_stop_words(arr):
    word_clean=[]
    for w in arr:
        if len(w)>=2 and w not in stop_words:
            word_clean.append(w)
    return word_clean

In [624]:
data_2023["words_clean"]=data_2023["words"].apply(lambda x:drop_stop_words(x))

In [625]:
data_2023.head()

,内容,relat,content2,words,words_clean,words_str
0,湛女士一直都很希望能够拥有自己的孩子，但是却发现自己并没有怀运的能力。因此，她决定做三代试管...,是,湛女士一直都很希望能够拥有自己的孩子但是却发现自己并没有怀运的能力因此她决定做三代试管试试不...,"[湛, 女士, 一直, 都, 很, 希望, 能够, 拥有, 自己, 的, 孩子, 但是, 却...","[希望, 拥有, 孩子, 发现自己, 能力, 三代, 试管, 试试, 不幸, 子宫, 发育不...",希望 拥有 孩子 发现自己 能力 三代 试管 试试 不幸 子宫 发育不全 第一次 尝试 成功...
1,苗女士在二十六岁的时候就开始出现一些怪异的身体现象。医生告诉她这是因为她的卵巢衰退了。这意味...,是,苗女士在二十六岁的时候就开始出现一些怪异的身体现象医生告诉她这是因为她的卵巢衰退了这意味着她...,"[苗, 女士, 在, 二十六岁, 的, 时候, 就, 开始, 出现, 一些, 怪异, 的, ...","[二十六岁, 怪异, 身体, 现象, 医生, 告诉, 卵巢, 衰退, 意味着, 永远, 失望...",二十六岁 怪异 身体 现象 医生 告诉 卵巢 衰退 意味着 永远 失望 想要 孩子 听说 三...
2,如果是不孕不育的问题不太严重，可以先尝试在国内做第一代、第二代试管，如果失败了再考虑去国外或...,是,如果是不孕不育的问题不太严重可以先尝试在国内做第一代第二代试管如果失败了再考虑去国外或者国外...,"[如果, 是, 不孕, 不育, 的, 问题, 不太, 严重, 可以, 先, 尝试, 在, 国...","[不孕, 不育, 不太, 尝试, 国内, 第一代, 第二代, 试管, 失败, 国外, 国外,...",不孕 不育 不太 尝试 国内 第一代 第二代 试管 失败 国外 国外 做代 一般来说 国外 ...
3,国内女客人和先生毕业就结婚了，因为年轻没想着要孩子，结婚3年后，想要孩子结果备孕了两年一直没...,是,国内女客人和先生毕业就结婚了因为年轻没想着要孩子结婚年后想要孩子结果备孕了两年一直没有成功喝...,"[国内, 女, 客人, 和, 先生, 毕业, 就, 结婚, 了, 因为, 年轻, 没, 想着...","[国内, 客人, 毕业, 结婚, 年轻, 想着, 孩子, 结婚, 想要, 孩子, 备孕, 两...",国内 客人 毕业 结婚 年轻 想着 孩子 结婚 想要 孩子 备孕 两年 成功 半年 中药 调...
4,绝育复通术后，促排三个月，成功怀孕，每天都有好消息，快来点赞接好孕呀！ 2国内·国内五洲妇儿...,是,绝育复通术后促排三个月成功怀孕每天都有好消息快来点赞接好孕呀国内国内五洲妇儿医院宝宝梦工场周...,"[绝育, 复通, 术后, 促排, 三个, 月, 成功, 怀孕, 每天, 都, 有, 好消息,...","[绝育, 复通, 术后, 促排, 三个, 成功, 怀孕, 好消息, 快来点, 赞接, 好孕,...",绝育 复通 术后 促排 三个 成功 怀孕 好消息 快来点 赞接 好孕 国内 国内 妇儿 医院...

In [626]:
data_2023["words_str"]=data_2023["words_clean"].apply(lambda x:" ".join(x))

In [627]:
#将文本中的词语转换为词频矩阵  
vectorizer = CountVectorizer()  
#计算个词语出现的次数  
X = vectorizer.fit_transform(data_2023["words_str"])  
#获取词袋中所有文本关键词  
word = vectorizer.get_feature_names()  
print (word)
#查看词频结果  
print(X.toarray())

['一万', '一上午', '一下子', '一不爱', '一丝', '一两个', '一两周', '一两天', '一两年', '一个个', '一个劲', '一个半月', '一个多月', '一个巴掌拍不响', '一个月', '一个点', '一个男孩', '一个遍', '一为', '一举', '一二', '一产个', '一人', '一代', '一件', '一份', '一会', '一会儿', '一位', '一住', '一体', '一例', '一侧', '一促', '一倍', '一做', '一做式', '一儿', '一共', '一关', '一具', '一册', '一再', '一击', '一刀', '一分', '一分收获', '一分耕耘', '一分钱', '一切正常', '一切都在', '一切都是', '一切顺利', '一利有', '一到', '一刹那', '一刻', '一刻起', '一剂', '一副', '一功', '一动不动', '一劳永逸', '一医', '一千', '一千多万', '一千多公里', '一半', '一半左右', '一去不复返了', '一取', '一口', '一口气', '一句', '一句句', '一只', '一台', '一号', '一同', '一名', '一向', '一听', '一员', '一周', '一味', '一哄而上', '一嘴', '一回', '一团', '一圈', '一场', '一坐', '一块', '一堆', '一声', '一备', '一大', '一大半', '一大堆', '一大早', '一大步', '一大笔', '一大部分', '一天到晚', '一天天', '一头雾水', '一套', '一女', '一好', '一孩', '一孩二孩三孩', '一定量', '一家', '一家人', '一家子', '一家老小', '一对', '一对一', '一封', '一封信', '一小', '一小部分', '一少', '一层', '一屋', '一岁', '一己', '一帆风顺', '一年', '一年之计在于春', '一年四季', '一并', '一度', '一座', '一张', '一心', '一忍', '一念之差', '一性', '一患', '一成', '一成不变', '一手', '一批', '一把', '一抱', '一拖再拖', '一招', '一排', '一搏', '一支', '一文', '一方', '一旁', '一无所获', '一日', '一日三餐', '一早', '一时间', '一是', '一晃', '一月', '一月份', '一有', '一朝', '一朝一夕', '一朵', '一束', '一条', '一条条', '一条龙', '一杯', '一松', '一枚', '一架', '一查', '一根', '一案', '一棵', '一概而论', '一次性', '一次次', '一款', '一止', '一步', '一步到位', '一步步', '一段', '一段时间', '一氧化氮', '一氧化碳', '一水', '一治', '一波', '一波三折', '一流', '一浅', '一浅怀', '一深', '一清二楚', '一滩', '一滴', '一炷香', '一点', '一点一点', '一点几', '一点点', '一环', '一瓶', '一生', '一用', '一男一女', '一番滋味', '一症', '一白', '一百余', '一百多', '一百多个', '一百天', '一盒', '一目了然', '一看', '一眨眼', '一瞬间', '一破', '一碰', '一磅', '一种', '一秒', '一移', '一站式', '一端', '一笑', '一笔', '一第', '一等', '一答', '一篇', '一类', '一系列', '一级', '一级预防', '一线', '一组', '一缕', '一群', '一聊', '一股', '一胎', '一胖毁', '一脸', '一臂之力', '一至', '一致性', '一般性', '一般来讲', '一般来说', '一般而言', '一般说来', '一行', '一要', '一觉', '一角', '一言难尽', '一词', '一试', '一说', '一财', '一超', '一超胎', '一趟', '一路', '一路上', '一路平安', '一蹴而就', '一身', '一身正气', '一车', '一轮', '一辈', '一辈子', '一过', '一连', '一连串', '一通', '一遍', '一道', '一遭', '一部分', '一针', '一门', '一问', '一阵儿', '一阵子', '一院', '一静', '一面面', '一项', '一顿', '一颗', '一齐', '丁克', '丁克家庭', '丁淑敏', '丁香', '七七', '七个', '七八', '七八个', '七夕', '七大', '七天', '七岁', '七年', '七成', '七斤', '七旬', '七月', '七月份', '七步', '七点', '七要', '七项', '七點', '万万不能', '万个', '万丽', '万事', '万事万物', '万事俱备', '万事兴', '万事大吉', '万事如意', '万人', '万人次', '万亿个', '万众', '万余人次', '万例', '万元', '万分之一', '万分感激', '万千', '万受', '万可', '万名', '万多', '万多元', '万左右', '万年', '万幸', '万无一失', '万日元', '万有', '万来', '万点', '万物', '万病', '万石', '万约', '万美元', '万能', '万里', '万金油', '丈夫', '三世', '三个', '三五天', '三亚', '三产', '三从四德', '三代', '三代人', '三位', '三低', '三体', '三倍体', '三分', '三分之一', '三分之二', '三到', '三十', '三十六岁', '三十四五岁', '三十多年', '三十年', '三取', '三口', '三叶草', '三周', '三四年', '三地', '三场', '三处', '三大', '三大块', '三大法宝', '三大类', '三大胎', '三天', '三套', '三季度', '三孩', '三孩先', '三宝', '三对', '三岁', '三年', '三度', '三微', '三忌', '三思', '三文鱼', '三方', '三是', '三月', '三月份', '三期', '三枚', '三柱', '三根', '三楼', '三次', '三步', '三水', '三点', '三甲', '三种', '三移', '三等奖', '三类', '三级', '三级预防', '三线', '三维', '三者', '三胎', '三胞胎', '三要', '三角', '三角区', '三超', '三轮', '三遍', '三酰', '三阴交', '三院', '三项', '三餐', '三高', '上万', '上上个月', '上下水', '上不动', '上个星期', '上个月', '上举', '上会', '上千', '上千年', '上升期', '上午', '上半身', '上古', '上周', '上周末', '上唇', '上垒', '上天', '上学', '上官', '上实', '上将', '上岸', '上市', '上帝', '上年', '上床', '上床睡觉', '上开', '上当', '上当受骗', '上微', '上德马', '上心', '上户', '上放', '上文', '上方', '上旬', '上极', '上榜', '上次', '上涨', '上火', '上环', '上班', '上用', '上百人', '上皮', '上皮组织', '上皮细胞', '上策', '上线', '上网', '上肢', '上臂', '上药', '上行', '上要', '上调', '上述情况', '上部', '上门', '上限', '上香会', '下一代', '下一阶段', '下丘脑', '下东', '下个', '下个月', '下于', '下仅', '下会', '下值', '下先', '下决心', '下况', '下前', '下力', '下功夫', '下加', '下午', '下半身', '下卡', '下取', '下周', '下周一', '下喜', '下囊性', '下圆', '下地', '下坠', '下垂', '下备', '下多', '下多囊', '下好', '下孕', '下定决心', '下宫', '下展', '下巴', '下庞', '下当', '下怀', '下意识', '下所能', '下手', '下才', '下斤', '下方', '下施', '下旬', '下时', '下期', '下柯', '下次', '下水', '下求', '下滑', '下漏', '下焦', '下班', '下璩', '下生会', '下用', '下电切术', '下痢', '下策', '下篇', '下糖', '下缘', '下肢', '下腹', '下腹部', '下若', '下血疗', '下行', '下要', '下试孕', '下贺', '下跌', '下载', '下部', '下降', '下降时', '下雨', '下颌部', '下馆子', '下鲜', '不上', '不不大用', '不中', '不为人知', '不乏', '不乘', '不争', '不争气', '不于', '不亚于', '不仅如此', '不介意', '不会错', '不传', '不伤', '不伴', '不低', '不住', '不佳', '不佳均', '不佳时', '不便', '不促', '不信', '不停', '不健', '不健运', '不像', '不全', '不公', '不净', '不准', '不减', '不出', '不利', '不利于', '不利因素', '不到', '不动', '不单单是', '不厌其烦', '不厚', '不去', '不及', '不可估量', '不可思议', '不可或缺', '不可言喻', '不可避免', '不吃', '不合理', '不同于', '不吸', '不和睦', '不哭', '不因', '不在乎', '不在少数', '不在此列', '不均', '不坏', '不堪', '不增', '不复', '不多', '不多别', '不多加', '不多时', '不多生', '不大备', '不大该', '不太', '不太会', '不太受', '不太可能', '不太多', '不太大', '不太好', '不太能', '不失为', '不好', '不好受', '不好意思', '不婚', '不孕', '不孕症', '不孝', '不孝有三', '不安', '不安全感', '不完全性', '不定期', '不宜', '不实入', '不容', '不容乐观', '不容忽视', '不寒', '不小', '不尽人意', '不尽相同', '不居大室', '不幸', '不幸遇害', '不应', '不延误', '不开', '不归路', '不当', '不必要', '不忍', '不忘', '不快', '不怀', '不思食', '不急来', '不惑', '不惑之年', '不惜代价', '不惧', '不想', '不愈', '不愧', '不愿', '不愿宫', '不懂事', '不懈', '不懈努力', '不成想', '不成才', '不成问题', '不戴套', '不才', '不抱', '不拿开', '不放过', '不敢相信', '不散', '不明', '不易', '不晚', '不来', '不正', '不死', '不求', '不治会', '不洁', '不润', '不清', '不清型', '不滞润', '不灵', '不燥', '不爱', '不爱长', '不爽', '不犟', '不甘', '不甚了解', '不生', '不用', '不用浪费', '不用说', '不畅', '不畏', '不留', '不疼', '不痛', '不相容', '不看', '不知', '不知情', '不知所措', '不破', '不确定性', '不禁', '不算', '不管不顾', '不肯', '不育', '不育症', '不胜感激', '不胜枚举', '不能到达', '不能抑制', '不能自己', '不腻', '不舒', '不舒之人', '不良', '不良习惯', '不良反应', '不良后果', '不良嗜好', '不良影响', '不良情绪', '不良现象', '不良行为', '不花', '不菲', '不行', '不要紧', '不见', '不见得', '不见森林', '不规则', '不解', '不言而喻', '不让', '不论是', '不设防', '不该', '不详', '不说', '不调', '不谈', '不负', '不负众望', '不负责任', '不贵', '不费周折', '不起眼', '不起经', '不足以', '不足者', '不辞辛劳', '不辞辛苦', '不过关', '不运仰', '不运症', '不远', '不远万里', '不远千里', '不退', '不适', '不适感', '不选', '不透气', '不通', '不遂', '不遇', '不配', '不长', '不间断', '不闹', '不难', '不需', '不靠', '不顺', '不顾一切', '不食', '不高', '不高当', '不麻', '与人为善', '与子', '与生俱来', '与量', '与非', '专业', '专业人士', '专业化', '专业知识', '专为', '专享', '专人', '专利', '专利技术', '专区', '专家', '专家团', '专家学者', '专家建议', '专家教授', '专家组', '专家论证', '专家门诊', '专属', '专座', '专批', '专攻', '专栏', '专治', '专注', '专用', '专用设备', '专病', '专看', '专研', '专科', '专科医生', '专科医院', '专科门诊', '专程', '专程来', '专精', '专精于', '专访', '专车', '专车接送', '专长', '专门从事', '专项', '专题', '专题报道', '且易消', '且级', '世人', '世卫', '世家', '世界', '世界卫生组织', '世界各地', '世界性', '世纪', '世间', '丙型肝炎', '丙烯酰胺', '丙瑞林来', '丙肝', '业余', '业余爱好', '业务', '业务人员', '业界', '业障', '丛可', '东北', '东北地区', '东南亚', '东南地区', '东南西北', '东奔西走', '东方', '东站', '东西', '丝助孕', '丝毫', '丝状', '丢失', '丢掉', '丢要', '两三个', '两三年', '两三颗', '两不误', '两个', '两为', '两人', '两人岁', '两亿', '两件', '两价', '两份', '两会', '两伤', '两位', '两侧', '两促', '两倍', '两儿', '两到', '两口子', '两名', '两周', '两回事', '两地', '两地分居', '两大', '两大类', '两天', '两头', '两女', '两女一男', '两家', '两尺', '两岁', '两岸三地', '两年', '两性', '两性之间', '两性关系', '两性生活', '两情', '两手抓', '两支', '两断', '两条', '两条腿走', '两枚', '两样', '两根', '两次', '两款', '两点', '两癌', '两种', '两移', '两类', '两粒', '两精', '两组', '两胎', '两虚', '两轮', '两边', '两透', '两道', '两间', '两难', '两项', '两颗', '两餐', '严凤英', '严咒', '严密', '严寒', '严峻', '严格执行', '严格要求', '严格遵守', '严禁', '严肃', '严谨', '严重危害', '严重后果', '严重威胁', '严重性', '严重破坏', '严重者', '丧命', '丧失', '个个', '个人化', '个人卫生', '个人见解', '个位数', '个体', '个体化', '个体差异', '个别人', '个备', '个头', '个子', '个巧囊', '个帅', '个性化', '个数', '个斤', '个案', '个长', '中上', '中下旬', '中东地区', '中人', '中仅', '中以', '中会', '中位', '中住', '中俄双', '中健', '中则', '中到', '中医', '中医医院', '中医学', '中医师', '中医疗法', '中医药', '中医药大学', '中医药学会', '中医院', '中午', '中午饭', '中华医学会', '中卓', '中南', '中即', '中原', '中取', '中右', '中叶', '中后', '中后期', '中含', '中国', '中国人民解放军', '中国医科大学', '中国外交部', '中国工程院', '中国科学院', '中均', '中塞成', '中备', '中多', '中多囊', '中奖', '中奖者', '中好', '中如', '中姚', '中子', '中孕', '中学', '中将', '中山', '中山大学', '中山市', '中巢', '中常', '中年', '中应', '中店', '中度', '中式', '中当', '中心', '中心医院', '中性', '中总有', '中成', '中成药', '中所受', '中所含', '中抗', '中招', '中断', '中方', '中旬', '中晏', '中晚期', '中曾', '中有', '中期', '中未', '中末', '中来', '中杯', '中枢', '中枢性', '中枢神经', '中止', '中正', '中段', '中毒', '中求', '中求阳', '中泡', '中炮', '中牟县', '中现', '中病', '中祝', '中秋', '中秋节', '中科院', '中空', '中等', '中等水平', '中糖', '中素', '中红', '中约', '中级', '中级会计', '中线', '中老年', '中耳炎', '中胚层', '中脘', '中膈', '中草药', '中药', '中药材', '中药饮片', '中西', '中西医', '中西药', '中要', '中译', '中该', '中贝', '中贺丹', '中路', '中转', '中载', '中边', '中过', '中选', '中选优', '中途', '中遇', '中部', '中醫', '中重型', '中重度', '中钟', '中长期', '中防变', '中隔', '中雨', '中雷', '中青年', '中颜值', '中风', '中飞出', '中餐', '中高危', '中鱼', '中黑', '丰厚', '丰县', '丰实', '丰收', '丰满', '丰辰', '串珠', '临值', '临床', '临床实践', '临床实验', '临床意义', '临床经验', '临床表现', '临床试验', '临时', '临武', '临沂', '临潼区', '临证', '临证会', '临走前', '临近', '临门一脚', '丹东', '丹参', '丹田', '丹皮', '丹麦', '为个', '为亥子', '为人所知', '为例', '为克子', '为克氏', '为准', '为君', '为啥', '为备', '为大补', '为天', '为娘', '为孕', '为宜', '为峡部', '为弱', '为怀', '为数不少', '为时不晚', '为易', '为母', '为注', '为生', '为病', '为种', '为胎', '为行', '为鉴', '为防', '为难', '为顺', '为首', '主义', '主义者', '主人翁', '主们', '主任', '主任医师', '主任医生', '主体', '主刀', '主力', '主力军', '主动', '主动权', '主咳', '主因', '主委', '主导', '主庙', '主意', '主成', '主打', '主持', '主持人', '主殿', '主气', '主治', '主治医师', '主治医生', '主流', '主痿', '主研人', '主神', '主管', '主管部门', '主营', '主要症状', '主观', '主诉', '主诊', '主语', '主调', '主选', '主题', '主食', '主餐', '主骨', '丽华', '举个', '举例', '举出', '举办', '举动', '举报', '举止', '举重', '乃是', '久久', '久坐', '久备', '久存', '久拖', '久服', '久治', '久治不愈', '久炎', '久病', '久而久之', '久远', '久违', '义务', '义诊', '之下', '之中', '之久', '之乐', '之事', '之二', '之余', '之光', '之内', '之分', '之初', '之剂', '之力', '之功', '之势', '之品', '之喜', '之外', '之府', '之弊', '之心', '之快', '之情', '之意', '之战', '之手', '之效', '之旅', '之旨', '之时', '之星', '之本', '之标', '之梦', '之母', '之气', '之法', '之海', '之源', '之火', '之爱', '之甘温', '之症', '之痛', '之神', '之称', '之精', '之脏', '之膜', '之至数', '之苦', '之药', '之药服', '之计', '之证', '之谜', '之象治', '之财', '之责', '之路', '之间', '之险', '之难', '之音', '乌药', '乌贼骨', '乌镇', '乌鸡', '乌鸦', '乌龟', '乍一看', '乏力', '乏氧', '乐器', '乐观', '乐趣', '乔杰', '乖乖', '乖巧', '乘坐', '乘车', '乙型肝炎', '乙烯', '乙肝', '乙肝疫苗', '乙肝病毒', '乙酉', '乙酰', '乙醇', '九个', '九九八十一', '九价', '九价九价', '九六年', '九制', '九千', '九只', '九周', '九四', '九因', '九型', '九子', '九子生', '九州', '九年', '九成', '九斤', '九月', '九月初', '九焉', '九瘤', '九蒸', '九龙', '乞西柚', '也备', '也许', '习惯', '习惯于', '习惯性', '书写', '书房', '买下来', '买不到', '买件', '买单', '买大', '买房', '买药', '买验', '乱了阵脚', '乱换', '乱换生', '乱用', '乱补', '乳凝', '乳制品', '乳头', '乳房', '乳抑', '乳晕', '乳汁', '乳白色', '乳胶', '乳腺', '乳腺炎', '乳腺病', '乳腺癌', '乳都', '乳酸', '乳酸杆菌', '乳酸菌', '乳量', '乾宫入', '了不起', '了程', '了结', '予以', '争先恐后', '争分夺秒', '争吵', '争夺', '争气', '争议', '争论', '事上', '事与愿违', '事业', '事业兴旺', '事业有成', '事事', '事以', '事件', '事倍功半', '事儿', '事先', '事务所', '事半功倍', '事后', '事备', '事多囊', '事宜', '事实', '事实上', '事实证明', '事快', '事怀', '事态', '事情', '事故', '事无巨细', '事物', '事甲减', '事说', '事里', '事难', '事项', '二七', '二三十', '二三十岁', '二个', '二个月', '二人', '二代', '二价', '二位', '二促', '二倍体', '二值', '二到', '二十', '二十个', '二十二', '二十余', '二十余位', '二十余年', '二十八', '二十六岁', '二十六年', '二十几岁', '二十分钟', '二十四', '二十四节气', '二十多岁', '二十年', '二取', '二周', '二地', '二型', '二多囊', '二天', '二婚', '二孕', '二孩', '二孩三孩且', '二孩及', '二宝', '二宝们', '二宝斤', '二年', '二弱', '二微', '二性', '二手烟', '二打', '二是', '二月', '二有', '二极体', '二楼', '二次', '二段', '二氧化氮', '二氧化硫', '二点', '二甲', '二看', '二种', '二精浆', '二级', '二线', '二组', '二维', '二维码', '二者', '二聚体', '二胎', '二脉', '二要', '二超', '二超后', '二超胎', '二阳', '二阳来', '二非', '二龙', '于始', '于温', '于身', '于针', '于雷', '于颈宫', '亏损', '亏者', '亏落', '亏虚', '云南', '云快', '云治', '云肝血', '云贵川', '云霞', '互享', '互动', '互相推诿', '互联网', '五一', '五个', '五位', '五六万', '五六年', '五六次', '五分', '五十年', '五千多万', '五卖', '五周', '五味子', '五味杂陈', '五大', '五天', '五子', '五子生', '五官', '五岁', '五岳', '五年', '五年级', '五微', '五成', '五星级', '五是', '五月', '五月份', '五术', '五条', '五杯', '五次', '五点', '五环', '五百', '五种', '五科', '五红汤', '五组', '五经', '五脏', '五脏六腑', '五行', '五行生克', '五要', '五谷', '五谷丰登', '五邑', '五项', '井冈山', '亚健康', '亚型', '亚心', '亚洲', '亚洲地区', '亚甲蓝', '亚运会', '亚马逊', '亚麻', '亚麻油', '亚麻酸', '些许', '亢奋', '亢盛', '亢进', '亢进症', '交了', '交代', '交叉', '交叉口', '交合', '交好', '交差', '交心', '交感神经', '交房', '交换', '交替', '交流', '交流会', '交班', '交由', '交给', '交谈', '交通', '交通事故', '交配', '交错', '亦可', '产一女', '产下', '产不', '产业', '产中', '产也会', '产产', '产会', '产伤', '产儿', '产出', '产前', '产前检查', '产前诊断', '产后', '产品', '产女', '产奶', '产妇', '产子', '产房', '产期', '产检', '产检中', '产检代', '产检卡', '产检是', '产检照', '产检超', '产检都', '产物', '产科', '产科医生', '产科医院', '产程', '产精', '产者', '产道', '产重', '产量', '亨特', '亨通', '享受', '享好孕', '享孕', '京子', '京豫', '亮相', '亮红灯', '亲临', '亲人', '亲们', '亲传', '亲切', '亲子', '亲子关系', '亲密关系', '亲属', '亲情', '亲戚', '亲戚朋友', '亲朋好友', '亲测', '亲爱', '亲生', '亲生父母', '亲生骨肉', '亲诊', '亲身经历', '亲近', '亳州', '人一', '人丁兴旺', '人世间', '人为', '人之常情', '人争', '人人喊打', '人仅', '人仲景', '人会', '人会用', '人住', '人体', '人促', '人儿', '人兴', '人其', '人则', '人别', '人到', '人到中年', '人医', '人参', '人取', '人变', '人口', '人口众多', '人口减少', '人口数', '人口数量', '人口素质', '人口老龄化', '人可觉', '人呆久', '人员', '人员配备', '人均', '人型', '人士', '人备', '人多', '人大', '人妻', '人宫', '人山人海', '人岁', '人巢会', '人工', '人工受孕', '人工合成', '人工呼吸', '人工干预', '人工授精', '人工控制', '人工智慧', '人工流产', '人常', '人得', '人微', '人心', '人性', '人性化', '人想', '人愿', '人房', '人才', '人授', '人数', '人易', '人有', '人未', '人来', '人格', '人母', '人民币', '人民日报', '人民法院', '人民网', '人流', '人满为患', '人生', '人生地不熟', '人生大事', '人生旅途', '人用', '人皆有之', '人祝', '人移', '人类', '人类文明', '人经', '人缘', '人群', '人能', '人舟', '人若', '人药流', '人要', '人见人爱', '人财', '人轻', '人造', '人造奶油', '人间', '人际关系', '人静', '亿元', '亿对', '亿有', '亿此', '亿美元', '亿者', '什说', '仁克', '仁德', '仁心', '仁济', '仁爱', '仅万人', '仅为', '仅供', '仅供参考', '仅剩', '仅售元', '仅次于', '仅用', '仅能', '仅远', '仅限', '今回', '今夜', '今天上午', '今天下午', '今带', '今年夏天', '今年年初', '今日', '今晚', '今来院', '今特', '介入', '介入性', '介绍', '介质', '仍在院', '仍能', '从业', '从业者', '从久备', '从人', '从今天起', '从养', '从刚', '从前', '从医', '从升', '从受', '从备', '从学', '从容应对', '从岁', '从巢', '从未有过', '从术', '从来不', '从根本上', '从次', '从江', '从没', '从流', '从用', '从线', '从那以后', '仓库', '仔仔', '仔子', '仔细', '仔细检查', '仕途', '他俩', '他家', '他选', '他院', '付出', '付娜', '付诸', '付钱', '仙女', '仙女们', '仙灵脾', '仙茅', '代代相传', '代价', '代偿', '代名词', '代孕', '代数', '代是', '代母', '代给', '代萌岁', '代表', '代表性', '代言', '代言人', '代试', '代谢', '代谢性', '代谢物', '代谢率', '代购', '令人', '令人心醉', '令人感动', '令人振奋', '令人满意', '令人激动', '令人难忘', '令人高兴', '令其', '以下内容', '以下几点', '以个', '以产', '以京豫', '以充', '以内', '以利', '以助', '以助阳', '以含', '以备', '以多囊', '以天', '以孕', '以官', '以客', '以宫', '以常', '以平', '以往', '以情', '以房', '以抑', '以提', '以日', '以时', '以末次', '以此', '以治', '以淡盐', '以清', '以滋肾', '以畅', '以致于', '以菌治菌', '以衡', '以超', '以较', '以辣为', '以运化', '以防', '以防万一', '仪器', '仪式', '仰卧起坐', '仰慕', '仰赖', '仲景', '价值', '价只', '价昂', '价格', '价格便宜', '价格比', '任二妮', '任人宰割', '任何一方', '任何人', '任其发展', '任地', '任意', '任斌', '任由', '任职', '任脉', '份量', '仿佛', '仿模佳茵', '仿照', '企业', '伉俪', '伊丽莎白', '伊乳杆', '伊利诺伊大学', '伊孕', '伍珠岁', '伍红岁', '伏案', '伏消', '伏笔', '休克', '休养', '休养生息', '休息', '休息区', '休息天', '休息日', '休息时间', '休整', '休诊', '休闲', '众多', '众苦', '优于', '优先', '优先选择', '优劣', '优势', '优化', '优卵', '优孕', '优异', '优惠', '优惠机票', '优点', '优生', '优生优育', '优甲乐', '优秀', '优绣', '优缺点', '优育', '优胜', '优胜劣汰', '优胜者', '优良', '优贝智', '优贝贝', '优质', '优越性', '优选', '优雅', '伙伴', '会上', '会不佳', '会为', '会令', '会伤', '会先', '会准', '会到', '会制', '会变', '会合', '会员', '会因', '会多取', '会大', '会导', '会少', '会得', '会怀', '会想', '会排', '会撑', '会机', '会测', '会涂', '会滑胎', '会演', '会烂', '会生', '会考', '会聚', '会胀', '会胎', '会花', '会要', '会计', '会议', '会诊', '会迎', '会长', '会间', '会阴', '会面', '会高', '伞端', '伞端动', '伞部', '传下来', '传好', '传宗', '传宗接代', '传承', '传授', '传播', '传来', '传染', '传染性', '传染病', '传染科', '传给', '传统', '传统医学', '传统观念', '传言', '传输', '传递', '伤二', '伤到', '伤口', '伤官', '伤害', '伤心', '伤心地', '伤敌', '伤残', '伤疤', '伤痛', '伤肝', '伤身', '伦理', '伦理学', '伪劣产品', '伪装', '伯伯', '伯明翰', '估算', '估计', '伴侣', '伴发', '伴娘', '伴有', '伴未', '伴未孕', '伴随', '伶俐', '伸入', '伸出', '伸展', '伸长', '伽蓝', '但九价', '但二孩三孩', '但于', '但会', '但值', '但备', '但小编', '但常', '但应', '但必', '但求', '但生', '但胜', '但阳康', '位于', '位列', '位地', '位宝', '位居', '位有', '位症', '位移', '位置', '位部', '位验孕', '低下', '低且', '低于', '低于正常', '低会', '低促', '低值', '低剂量', '低助孕', '低升糖', '低取', '低多囊', '低头', '低年', '低廉', '低得', '低成本', '低收入', '低敏', '低无创', '低时', '低景门', '低有', '低水平', '低温', '低生', '低碳', '低等', '低糖', '低级', '低经', '低肌', '低胖', '低脂', '低至元', '低落', '低超', '低过', '低限', '低频', '低高', '住在一起', '住宿', '住房', '住所', '住满', '住进', '住院', '住院治疗', '体会', '体位', '体健', '体内', '体况', '体力', '体力劳动', '体力活', '体味', '体型', '体外', '体外受精', '体寒', '体寒型', '体建', '体形', '体征', '体态', '体操', '体来', '体格', '体格检查', '体检', '体毛', '体液', '体温', '体温表', '体现', '体病', '体积', '体系', '体细胞', '体育', '体育场', '体育锻炼', '体能', '体脂', '体谅', '体质', '体贴', '体部', '体重', '体重儿', '体重减轻', '体重增加', '体长', '体验', '体魄', '佔据', '何信', '何嫦岁', '何岁', '何清岁', '何玲岁', '何琴', '何种', '何菁岁', '何谈', '何金', '何金苏', '何静', '何首乌', '余下', '余丽岁', '余例', '余姚', '余岁', '余年', '余悸', '余枚', '余生', '余种', '佛争', '佛光', '佛前', '佛力', '佛印', '佛山市', '佛教', '佛母', '佛气', '佛祖', '佛系', '佛陀', '作业', '作主', '作出', '作发', '作好', '作怪', '作息', '作息时间', '作战', '作抑', '作文', '作用', '作祟', '作者', '你准', '你否', '你好', '你学', '你家', '你常', '佩带', '佩戴', '佩服', '佳佳', '佳约', '佳能', '佳节', '佳茵买', '佳茵以', '佳茵有', '佳茵里', '佳音', '佼佼者', '使人', '使体', '使供', '使劲', '使命', '使子', '使性', '使本', '使生', '使用不当', '使用方便', '使用率', '使用量', '使血', '侃侃而谈', '例假', '例占', '例外', '例外情况', '例多囊', '例子', '例月', '例行', '侏儒症', '供体', '供使', '供卵供', '供取', '供奉', '供应', '供用', '供精', '供给', '供者', '供能', '供血', '供血供', '供选择', '供随', '供需', '依从性', '依依', '依依不舍', '依偎', '依托', '依旧', '依法', '依然', '依赖', '依赖于', '依赖性', '侥幸', '侥幸心理', '侦办', '侧切', '侧卧', '侧卧位', '侧弯', '侯加运', '侯英岁', '侵入', '侵害', '侵扰', '侵权', '侵染', '侵犯', '侵略', '侵蚀', '侵袭', '侵袭到', '便会', '便利', '便宜', '便捷', '便是', '便来', '便次', '便涩', '便秘', '促三移', '促了', '促使', '促六移', '促取', '促好', '促孕', '促性', '促性素', '促性腺激', '促性腺素', '促成', '促排', '促排卵', '促排期', '促排物', '促攒', '促泡', '促炎', '促生', '促破', '促移', '促育', '促能取', '促黄体素', '俄勒冈', '俄勒冈州', '俄待', '俗人', '俗称', '俗话说', '俗话说得好', '保不住', '保住', '保佑', '保健', '保健品', '保健法', '保健酒', '保健院', '保兰', '保养', '保到', '保助孕', '保单', '保卫', '保存', '保存起来', '保守', '保安', '保定', '保宫', '保宫金', '保得住', '保护', '保护性', '保护措施', '保持联系', '保持良好', '保暖', '保有', '保水', '保温杯', '保温箱', '保湿', '保物', '保留', '保研', '保管费', '保育费', '保胎', '保证', '保证书', '保质期', '保障', '保障局', '保驾护航', '信以为真', '信仰', '信件', '信任', '信使', '信号', '信士', '信心', '信念', '信息', '信服', '信群', '信誉', '信赖', '信都区', '俨然', '俭岁', '修养', '修复', '修学', '修成', '修改', '修整', '修正', '修炼', '修缮', '修补', '修补术', '修订', '修路', '俱乐部', '俱佳', '俱惫', '俺家', '倍增', '倍数', '倍率', '倒入', '倒数', '倒数第', '倒流', '倒经', '倒置', '倒计时', '倒闭', '倒霉', '候珍', '候阴菌', '倚靠', '借个', '借助', '借卵', '借口', '借来', '借用', '借由', '借鉴', '倡导', '倡议', '倦怠', '值不高', '值仅', '值会', '值低', '值入', '值及', '值得', '值有', '值比', '值测', '值班', '值血氧', '值越', '值较', '值过', '值高值', '倾力', '倾向', '倾听', '倾尽', '倾屈', '倾情', '倾斜', '倾注', '倾诉', '假以时日', '假休', '假取', '假大', '假孕', '假性', '假日', '假期', '假设', '假象', '偏于', '偏位', '偏低', '偏厚', '偏向', '偏大', '偏大才', '偏头痛', '偏小', '偏小双侧', '偏小对', '偏慢', '偏方', '偏爱', '偏瘦', '偏胖', '偏薄', '偏薄备', '偏虚', '偏衰', '偏见', '偏食', '偏高', '偏高且', '偏高会', '偏高则', '偏高到', '偏高备', '偏高弱', '偏高经', '偏黄', '做下', '做不了', '做个', '做事', '做二超', '做些', '做产前', '做产检', '做人', '做人流', '做代', '做代鲜', '做会', '做何', '做佳茵到', '做供', '做做', '做全', '做冻', '做出', '做前', '做卷', '做备', '做复', '做多囊', '做太多', '做好', '做孕', '做孕检', '做宫', '做式', '做得好', '做成', '做手术', '做抚触', '做排', '做梦', '做检', '做步', '做法', '做流', '做画', '做管', '做经', '做试', '做起', '做超', '做过', '做通', '做遍', '做饭', '停下来', '停史', '停后', '停孕', '停指', '停掉', '停来', '停次', '停歇', '停止', '停止使用', '停滞', '停滞不前', '停率', '停用', '停留', '停经', '停聚', '停育', '停育史', '停育备', '停育案', '停育次', '停育胎', '停胎', '停胎育', '停药', '停要', '停车', '健不', '健健康康', '健全', '健康', '健康人', '健康成长', '健康检查', '健康状况', '健忘', '健步如飞', '健牌', '健管', '健脾', '健身', '健身房', '健身操', '健身运动', '健院', '偶发', '偶有', '偶然', '偷偷', '偷偷摸摸', '偷窥', '偷走', '傅丽萍', '傅山', '傅青主', '傍晚', '储备', '储备量', '储存', '储水', '储肥', '催乳', '催乳素', '催产', '催产素', '催促', '催熟', '催生', '傻傻', '像是', '僧伽', '僵硬', '儿和围', '儿型', '儿女', '儿媳', '儿子', '儿科', '儿科医生', '儿科医院', '儿童', '儿童医院', '儿童期', '儿童节', '儿茶素', '儿茶酚', '儿茶酚胺', '元之方', '元元元', '元凶', '元备', '元宝', '元宵', '元旦', '元旦假期', '元气', '元气大伤', '元素', '元超', '元阳', '元隆', '元高', '兄妹', '兄弟', '兄弟俩', '充不', '充养', '充分准备', '充分利用', '充分发挥', '充分条件', '充分考虑', '充分肯定', '充分说明', '充分调动', '充分运用', '充助', '充当', '充数', '充斥', '充沛', '充满', '充满希望', '充生', '充盈', '充盛', '充维素', '充血', '充补该', '充裕', '充质', '充足', '充酸菌', '兆头', '先不说', '先临', '先为', '先于', '先亲', '先促', '先兆', '先决条件', '先别', '先到', '先前', '先去', '先备', '先天', '先天不足', '先天之精', '先天性', '先对', '先已', '先得', '先必', '先找', '先敏', '先易后难', '先是', '先有', '先来', '先查', '先治好', '先煎克川', '先王', '先用', '先男后', '先看', '先祖', '先行', '先要', '先试', '先说', '先调', '先进', '先进性', '先进设备', '先防', '先飞', '先马住', '光临', '光备', '光学', '光明', '光泽', '光滑', '光片', '光芒', '光调', '光谱', '光阴', '光靠', '光顾', '克仙', '克山', '克巴戟', '克拉', '克日', '克日服', '克星', '克服', '克林', '克氏', '克盐', '克米芬', '克罗米', '克脾土会', '克赤', '克食', '免力', '免受', '免得', '免收', '免疫', '免疫刺激', '免疫力', '免疫原性', '免疫增强', '免疫学', '免疫性', '免疫抑制', '免疫抗体', '免疫治疗', '免疫病', '免疫科', '免疫系统', '免疫组化', '免疫耐受', '免疫调节', '免责', '免费', '免除', '兑服', '兑现', '兔子', '兔宝', '兔年', '党参', '入不敷出', '入世', '入住', '入侵', '入侵者', '入厕', '入口处', '入周', '入境', '入怀', '入手', '入眠', '入睡', '入编', '入药', '入营', '入院', '全世界', '全会', '全体会议', '全免', '全切', '全切术', '全力以赴', '全力支持', '全取', '全台', '全国', '全国妇联', '全城', '全多囊', '全天', '全套', '全家', '全家人', '全家福', '全封闭', '全心', '全心全意', '全性', '全息', '全攻全守', '全攻略', '全文', '全新', '全方', '全方位', '全方滋而', '全是', '全景', '全梗右', '全没', '全满', '全然不顾', '全熟', '全球', '全球化', '全球性', '全用', '全省', '全称', '全程', '全线', '全组', '全美', '全职', '全胚', '全貌', '全身', '全身性', '全过程', '全部内容', '全部都是', '全长约', '全院', '全靠', '全面推行', '全额', '全麦', '全麻', '八两', '八九',

In [628]:
#词的维度
print(len(word))

21198

In [629]:
#文本表述维度
X.toarray().shape

(4708, 21198)

In [630]:
#类调用  
transformer = TfidfTransformer()  
#将词频矩阵X统计成TF-IDF值  
tfidf = transformer.fit_transform(X)  
#查看数据结构 tfidf[i][j]表示i类文本中的tf-idf权重  
print(tfidf.toarray()  )

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

In [631]:
#查看第一个文本的词的tfidf值
for i in tfidf.toarray()[0]:
    if i!=0:
        print(i)

0.13196595832138708
0.18033737428775068
0.18688291303535123
0.13519560136531228
0.13072405876468576
0.21543382972256797
0.17165228474257088
0.17756609148260583
0.2670674391286966
0.11998694032367366
0.19547101572616693
0.1750471085424685
0.07870817052634371
0.0952823622138798
0.18688291303535123
0.13196595832138708
0.10875972557323019
0.18183448043084993
0.15467559440867196
0.19306169518129337
0.16784080808256677
0.12543379301940358
0.14231803011678762
0.16768986264904048
0.20102753081716063
0.21225474556760413
0.16114432390143996
0.1514142152940957
0.19306169518129337
0.16862858707544565
0.11901527155238072
0.12953547635506946
0.1405309766268625
0.0757536747652355
0.1908453351288816
0.24267501070435832

In [632]:
k=3

In [633]:
#LDA主题建模
#设置主题数量，学习方式，超参数α，β取默认值。
lda = LatentDirichletAllocation(n_components=k, learning_method='batch', max_iter=50, random_state=0)
lda_topics = lda.fit_transform(tfidf.toarray())

In [634]:
#对主题词做降序排列
sorting = np.argsort(lda.components_, axis=1)[:, ::-1]
feature_names = np.array(vectorizer.get_feature_names())

mglearn.tools.print_topics(topics=range(k), feature_names=feature_names,
                           sorting=sorting, topics_per_chunk=5, n_words=20)

topic 0       topic 1       topic 2
--------      --------      --------
国内            国内            客人
烧香            医院            国外
阿姨            不孕            宝宝
日记            阳光            试管
前列腺炎          怀孕            赴美
早泄            输卵管           移植
阳痿            不育            生命
祈福            子宫            期待
烧香拜佛          医生            可爱
大庙            治疗            幸福
肾虚            女性            宝妈
失眠            检查            爱心
攻略            卵巢            试管婴儿
注意事项          试管            咨询中心
菩萨            备孕            单身
求子            试管婴儿          妈妈
朋友            时间            顺利
调理            内膜            出生
心愿            妇科            家庭
加持            导致            生子

In [564]:
for k in range(3,7):
    print("============"+str(k)+"============")
    #LDA主题建模
    #设置主题数量，学习方式，超参数α，β取默认值。
    lda = LatentDirichletAllocation(n_components=k, learning_method='batch', max_iter=50, random_state=0)
    lda_topics = lda.fit_transform(tfidf.toarray())
    #对主题词做降序排列
    sorting = np.argsort(lda.components_, axis=1)[:, ::-1]
    feature_names = np.array(vectorizer.get_feature_names())

    mglearn.tools.print_topics(topics=range(k), feature_names=feature_names,
                               sorting=sorting, topics_per_chunk=5, n_words=20)

============3============
topic 0       topic 1       topic 2
--------      --------      --------
国内            试管            不孕
阳光            客人            子宫
医院            国内            女性
输卵管           宝宝            不育
不孕            国外            治疗
妈妈            女士            检查
主任            成功            怀孕
医生            赴美            卵巢
时间            孩子            导致
怀孕            移植            内膜
好孕            试管婴儿          输卵管
就诊            顺利            影响
复通            生命            试管婴儿
粘连            烧香            医院
未孕            幸福            卵泡
宝宝            出生            精子
怀上            可爱            月经
主诊            三代            国内
手术            妈妈            原因
收起            期待            情况


============4============
topic 0       topic 1       topic 2       topic 3
--------      --------      --------      --------
国内            提问            不孕            国内
阳光            开课            女性            客人
医院            八字            子宫            试管
输卵管           只想            不育            宝宝
妈妈            化解            治疗            国外
主任            破解            怀孕            女士
不孕            秋波            检查            成功
医生            上德马           卵巢            赴美
时间            添丁            医院            移植
怀孕            须知            导致            孩子
就诊            窗口期           影响            试管婴儿
复通            合十            试管婴儿          顺利
好孕            青素            内膜            生命
粘连            预判            国内            烧香
未孕            姐个            输卵管           幸福
宝宝            发呆            卵泡            可爱
怀上            乙肝            精子            妈妈
主诊            四部曲           月经            家庭
收起            东西            妇科            期待
手术            定心丸           收起            出生


============5============
topic 0       topic 1       topic 2       topic 3       topic 4
--------      --------      --------      --------      --------
阳光            幸福            不孕            国内            试管
国内            爱心            不育            烧香            试管婴儿
医院            生命            医院            会诊            客人
输卵管           咨询中心          输卵管           前列腺炎          国外
妈妈            妈妈            妇科            早泄            怀孕
时间            可爱            国内            阳痿            卵巢
不孕            宝宝            子宫            祈福            宝宝
主任            期待            导致            烧香拜佛          女性
医生            美好            女性            大庙            胚胎
怀孕            生殖            蕴育            教授            移植
复通            家庭            治疗            肾虚            成功
就诊            充满            检查            攻略            卵泡
粘连            提问            男性            失眠            治疗
未孕            开课            炎症            菩萨            检查
好孕            未来            专业            求子            子宫
宝宝            梦想            宫颈            调理            国内
主诊            奇迹            月经            博士            不孕
怀上            成长            影响            朋友            收起
结扎            渴望            内膜            注意事项          女士
手术            课堂            症状            祝福            备孕


============6============
topic 0       topic 1       topic 2       topic 3       topic 4
--------      --------      --------      --------      --------
得意            阳光            不孕            国内            试管
感恩            国内            女性            烧香            国内
孕吐            妈妈            子宫            祈福            客人
不好意思          医院            不育            烧香拜佛          国外
影响力           时间            导致            大庙            试管婴儿
三胞胎           宝宝            卵巢            攻略            宝宝
正面            复通            治疗            菩萨            女士
谢谢你们          就诊            检查            求子            成功
拍摄            输卵管           影响            注意事项          医院
夫人            医生            输卵管           心愿            不孕
真凶            未孕            怀孕            朋友            怀孕
传好            怀孕            内膜            祝福            移植
感受            主诊            月经            还神            好孕
新生            粘连            精子            加油            医生
困境            不孕            排卵            加持            输卵管
梨形            收起            男性            好运            备孕
腹胀            结扎            卵泡            灵验            孩子
好孕来           幸福            医院            所有人           主任
当上            梗阻            原因            达成            胚胎
看护            确诊            卵子            学业            治疗


topic 5
--------
医院
国内
妇科
蕴育
会诊
妇产医院
博士
不育
专家
诊疗
不孕
妇科医院
生殖
名医
教授
专注
专业
咨询
知识
品牌